--------------------------------------------------------
--  DDL for View V_ANAGRAFICO_TERZO
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "V_ANAGRAFICO_TERZO" ("CD_ANAG", "TI_ITALIANO_ESTERO", "TI_ENTITA", "TI_ENTITA_FISICA", "TI_ENTITA_GIURIDICA", "FL_SOGGETTO_IVA", "CODICE_FISCALE", "PARTITA_IVA", "ID_FISCALE_ESTERO", "RAGIONE_SOCIALE", "NOME", "COGNOME", "VIA_FISCALE", "NUM_CIVICO_FISCALE", "PG_COMUNE_FISCALE", "DS_COMUNE_FISCALE", "CD_PROVINCIA_FISCALE", "DS_PROVINCIA_FISCALE", "CAP_COMUNE_FISCALE", "FRAZIONE_FISCALE", "PG_NAZIONE_FISCALE", "TI_SESSO", "DT_NASCITA", "PG_COMUNE_NASCITA", "DS_COMUNE_NASCITA", "CD_PROVINCIA_NASCITA", "DS_PROVINCIA_NASCITA", "PG_NAZIONE_NAZIONALITA", "FL_FATTURAZIONE_DIFFERITA", "FL_OCCASIONALE", "CD_CLASSIFIC_ANAG", "CD_ATTIVITA_INPS", "ALTRA_ASS_PREVID_INPS", "ALIQUOTA_FISCALE", "CODICE_FISCALE_CAF", "DENOMINAZIONE_CAF", "SEDE_INAIL", "MATRICOLA_INAIL", "CONTO_NUMERARIO_CREDITO", "CONTO_NUMERARIO_DEBITO", "NUM_ISCRIZ_CCIAA", "NUM_ISCRIZ_ALBO", "DT_FINE_RAPPORTO", "CAUSALE_FINE_RAPPORTO", "DT_ANTIMAFIA", "CD_ENTE_APPARTENENZA", "CD_TERZO", "CD_PRECEDENTE", "PG_RAPP_LEGALE", "TI_TERZO", "DENOMINAZIONE_SEDE", "VIA_SEDE", "NUMERO_CIVICO_SEDE", "PG_COMUNE_SEDE", "DS_COMUNE_SEDE", "CD_PROVINCIA_SEDE", "DS_PROVINCIA_SEDE", "CAP_COMUNE_SEDE", "FRAZIONE_SEDE", "CD_UNITA_ORGANIZZATIVA", "NOME_UNITA_ORGANIZZATIVA", "NOTE", "DT_CANC", "DACR", "UTCR", "DUVA", "UTUV", "PG_VER_REC", "FL_CERVELLONE","FL_FIRMATARIO_CONTRATTO") AS
  SELECT
--
-- Date: 10/05/2001
-- Version: 1.0
--
-- Vista estrazione terzi con tutte le informazioni di base della anagrafica a cui appartengono--
--
-- History:
-- Date: 10/05/2001
-- Version: 1.0
-- Creazione
--
-- History:
-- Date: 13/02/2025
-- Version: 1.0
-- Aggiunto fl_firmatario_contratto
-- Body:
--
       T.CD_ANAG,
       A.TI_ITALIANO_ESTERO,
       A.TI_ENTITA,
       A.TI_ENTITA_FISICA,
       A.TI_ENTITA_GIURIDICA,
       A.FL_SOGGETTO_IVA,
       A.CODICE_FISCALE,
       A.PARTITA_IVA,
       A.ID_FISCALE_ESTERO,
       A.RAGIONE_SOCIALE,
       A.NOME,
       A.COGNOME,
       A.VIA_FISCALE,
       A.NUM_CIVICO_FISCALE,
       A.PG_COMUNE_FISCALE,
       C1.DS_COMUNE,
       C1.CD_PROVINCIA,
       P1.DS_PROVINCIA,
       A.CAP_COMUNE_FISCALE,
       A.FRAZIONE_FISCALE,
       A.PG_NAZIONE_FISCALE,
       A.TI_SESSO,
       A.DT_NASCITA,
       A.PG_COMUNE_NASCITA,
       C2.DS_COMUNE,
       C2.CD_PROVINCIA,
       P2.DS_PROVINCIA,
       A.PG_NAZIONE_NAZIONALITA,
       A.FL_FATTURAZIONE_DIFFERITA,
       A.FL_OCCASIONALE,
       A.CD_CLASSIFIC_ANAG,
       A.CD_ATTIVITA_INPS,
       A.ALTRA_ASS_PREVID_INPS,
       A.ALIQUOTA_FISCALE,
       A.CODICE_FISCALE_CAF,
       A.DENOMINAZIONE_CAF,
       A.SEDE_INAIL,
       A.MATRICOLA_INAIL,
       A.CONTO_NUMERARIO_CREDITO,
       A.CONTO_NUMERARIO_DEBITO,
       A.NUM_ISCRIZ_CCIAA,
       A.NUM_ISCRIZ_ALBO,
       A.DT_FINE_RAPPORTO,
       A.CAUSALE_FINE_RAPPORTO,
       A.DT_ANTIMAFIA,
       A.CD_ENTE_APPARTENENZA,
       T.CD_TERZO,
       T.CD_PRECEDENTE,
       T.PG_RAPP_LEGALE,
       T.TI_TERZO,
       T.DENOMINAZIONE_SEDE,
       T.VIA_SEDE,
       T.NUMERO_CIVICO_SEDE,
       T.PG_COMUNE_SEDE,
       C3.DS_COMUNE,
       C3.CD_PROVINCIA,
       P3.DS_PROVINCIA,
       T.CAP_COMUNE_SEDE,
       T.FRAZIONE_SEDE,
       T.CD_UNITA_ORGANIZZATIVA,
       T.NOME_UNITA_ORGANIZZATIVA,
       T.NOTE,
       T.DT_CANC,
       T.DACR,
       T.UTCR,
       T.DUVA,
       T.UTUV,
       T.PG_VER_REC,
       A.FL_CERVELLONE,
       A.FL_FIRMATARIO_CONTRATTO
FROM   TERZO T
LEFT JOIN ANAGRAFICO A ON A.CD_ANAG = T.CD_ANAG
LEFT JOIN COMUNE C1 ON C1.PG_COMUNE = A.PG_COMUNE_FISCALE
LEFT JOIN COMUNE C3 ON C3.PG_COMUNE = T.PG_COMUNE_SEDE
LEFT OUTER JOIN PROVINCIA P1 ON P1.CD_PROVINCIA = C1.CD_PROVINCIA
LEFT OUTER JOIN COMUNE C2 ON C2.PG_COMUNE = A.PG_COMUNE_NASCITA
LEFT OUTER JOIN PROVINCIA P2 ON P2.CD_PROVINCIA = C2.CD_PROVINCIA
LEFT OUTER JOIN PROVINCIA P3 ON P3.CD_PROVINCIA = C3.CD_PROVINCIA;
