--------------------------------------------------------
--  DDL for View V_BUONO_CARICO_INV
--------------------------------------------------------

CREATE OR REPLACE FORCE VIEW "V_BUONO_CARICO_INV" ("PG_BUONO_C_S", "TI_DOCUMENTO", "ESERCIZIO", "PG_INVENTARIO", "NR_INVENTARIO", "PROGRESSIVO", "DS_BENE", "CD_CDS_FATT_PASS", "CD_UO_FATT_PASS", "ESERCIZIO_FATT_PASS", "PG_FATTURA_PASSIVA", "PROGRESSIVO_RIGA_FATT_PASS", "CD_CDS_FATT_ATT", "CD_UO_FATT_ATT", "ESERCIZIO_FATT_ATT", "PG_FATTURA_ATTIVA", "PROGRESSIVO_RIGA_FATT_ATT", "CD_CDS_DOC_GEN", "CD_UO_DOC_GEN", "ESERCIZIO_DOC_GEN", "PG_DOCUMENTO_GENERICO", "PROGRESSIVO_RIGA_DOC_GEN", "CD_TIPO_DOCUMENTO_AMM") AS
  select
 BUONO.PG_BUONO_C_S,
  BUONO.TI_DOCUMENTO,
  BUONO.ESERCIZIO,
 BENE.PG_INVENTARIO              ,
  BENE.NR_INVENTARIO              ,
  BENE.PROGRESSIVO                ,
  BENE.DS_BENE                    ,
 ASS.CD_CDS_FATT_PASS           ,
  ASS.CD_UO_FATT_PASS            ,
  ASS.ESERCIZIO_FATT_PASS        ,
  ASS.PG_FATTURA_PASSIVA     ,
  ASS.PROGRESSIVO_RIGA_FATT_PASS ,
  ass.cd_cds_fatt_att          ,
  ass.cd_uo_fatt_att            ,
  ass.esercizio_fatt_att        ,
  ass.pg_fattura_attiva     ,
  ass.progressivo_riga_fatt_att ,
  ASS.CD_CDS_DOC_GEN    	,
  ASS.CD_UO_DOC_GEN      	,
  ASS.ESERCIZIO_DOC_GEN    	,
  ASS.PG_DOCUMENTO_GENERICO ,
  ASS.PROGRESSIVO_RIGA_DOC_GEN,
  ASS.CD_TIPO_DOCUMENTO_AMM
  from    BUONO_CARICO_SCARICO_DETT BUONO
        inner join INVENTARIO_BENI bene
        on  BUONO.PG_INVENTARIO = BENE.PG_INVENTARIO  And
            BUONO.NR_INVENTARIO = BENE.NR_INVENTARIO  And
            BUONO.PROGRESSIVO   = BENE.PROGRESSIVO
        left outer join   ASS_INV_BENE_FATTURA ASS
        on ASS.PG_INVENTARIO = BENE.PG_INVENTARIO  And
            ASS.NR_INVENTARIO = BENE.NR_INVENTARIO  And
            ASS.PROGRESSIVO   = BENE.PROGRESSIVO AND
            ASS.ESERCIZIO= BUONO.ESERCIZIO and
            ASS.PG_BUONO_C_S=BUONO.PG_BUONO_C_S and
            ASS.TI_DOCUMENTO=BUONO.TI_DOCUMENTO;