--------------------------------------------------------
--  DDL for View V_CONS_SALDI_RESIDUI_SPE_DET
--------------------------------------------------------


CREATE OR REPLACE FORCE VIEW "V_CONS_SALDI_RESIDUI_SPE_DET" (
    "ESERCIZIO",
    "ESERCIZIO_RES",
    "CD_CENTRO_RESPONSABILITA",
    "CD_LINEA_ATTIVITA",
    "TI_APPARTENENZA",
    "TI_GESTIONE",
    "CD_ELEMENTO_VOCE",
    "DS_ELEMENTO_VOCE",  -- NUOVO CAMPO
    "IM_STANZ_RES_IMPROPRIO",
    "PG_VAR_ST_RES",
    "DS_VAR_ST_RES",
    "VAR_PIU_ST_RES",
    "VAR_MENO_ST_RES",
    "CDS_OBB",
    "PG_OBB",
    "DS_OBBLIGAZIONE",  -- NUOVO CAMPO
    "PG_OBB_SCAD",
    "CD_TIPO_DOCUMENTO_CONT",
    "DS_SCADENZA",
    "IM_OBBL_RES_IMP",
    "IM_OBBL_RES_PRO",
    "PG_VAR_RES_PRO",
    "DS_VAR_RES_PRO",
    "VAR_PIU_OBB_RES_PRO",
    "VAR_MENO_OBB_RES_PRO",
    "CDS_MAN",
    "PG_MAN",
    "DS_MANDATO",
    "PAGATO_RES_PROPRIO",
    "PAGATO_RES_IMPROPRIO",
    "IMP_DOC_RES_PROPRIO",
    "IMP_DOC_RES_IMPROPRIO"
) AS
-- PRIMA PARTE: Da V_CONS_SALDI_RESIDUI_SPE
SELECT
    s.ESERCIZIO,
    s.ESERCIZIO_RES,
    s.CD_CENTRO_RESPONSABILITA,
    s.CD_LINEA_ATTIVITA,
    s.TI_APPARTENENZA,
    s.TI_GESTIONE,
    s.CD_ELEMENTO_VOCE,
    ev.DS_ELEMENTO_VOCE,  -- JOIN con elemento_voce
    s.IM_STANZ_RES_IMPROPRIO,
    s.PG_VAR_ST_RES,
    s.DS_VAR_ST_RES,
    s.VAR_PIU_ST_RES,
    s.VAR_MENO_ST_RES,
    s.CDS_OBB,
    s.PG_OBB,
    o.DS_OBBLIGAZIONE,  -- JOIN con obbligazione
    s.PG_OBB_SCAD,
    s.CD_TIPO_DOCUMENTO_CONT,
    s.DS_SCADENZA,
    s.IM_OBBL_RES_IMP,
    s.IM_OBBL_RES_PRO,
    s.PG_VAR_RES_PRO,
    s.DS_VAR_RES_PRO,
    s.VAR_PIU_OBB_RES_PRO,
    s.VAR_MENO_OBB_RES_PRO,
    s.CDS_MAN,
    s.PG_MAN,
    s.DS_MANDATO,
    s.PAGATO_RES_PROPRIO,
    s.PAGATO_RES_IMPROPRIO,
    0 IMP_DOC_RES_PROPRIO,
    0 IMP_DOC_RES_IMPROPRIO
FROM V_CONS_SALDI_RESIDUI_SPE s
LEFT OUTER JOIN elemento_voce ev
    ON s.ESERCIZIO = ev.ESERCIZIO
    AND s.CD_ELEMENTO_VOCE = ev.CD_ELEMENTO_VOCE
LEFT OUTER JOIN obbligazione o
    ON s.CDS_OBB = o.CD_CDS
    AND s.PG_OBB = o.PG_OBBLIGAZIONE
    AND s.ESERCIZIO = o.ESERCIZIO
    AND s.ESERCIZIO_RES = o.ESERCIZIO_ORIGINALE

UNION ALL

-- SECONDA PARTE: MANDATI RESIDUI PROPRI
SELECT
    o.ESERCIZIO,
    o.ESERCIZIO_ORIGINALE,
    osv.CD_CENTRO_RESPONSABILITA,
    osv.CD_LINEA_ATTIVITA,
    o.TI_APPARTENENZA,
    o.TI_GESTIONE,
    o.CD_ELEMENTO_VOCE,
    ev.DS_ELEMENTO_VOCE,  -- JOIN con elemento_voce
    0,  -- IM_STANZ_RES_IMPROPRIO
    NULL,  -- PG_VAR_ST_RES
    NULL,  -- DS_VAR_ST_RES
    0,  -- VAR_PIU_ST_RES
    0,  -- VAR_MENO_ST_RES
    osv.CD_CDS,  -- CDS_OBB
    osv.PG_OBBLIGAZIONE,  -- PG_OBB
    o.DS_OBBLIGAZIONE,  -- DS_OBBLIGAZIONE
    osv.PG_OBBLIGAZIONE_SCADENZARIO,  -- PG_OBB_SCAD
    o.CD_TIPO_DOCUMENTO_CONT,
    os.DS_SCADENZA,
    0,  -- IM_OBBL_RES_IMP
    0,  -- IM_OBBL_RES_PRO
    NULL,  -- PG_VAR_RES_PRO
    NULL,  -- DS_VAR_RES_PRO
    0,  -- VAR_PIU_OBB_RES_PRO
    0,  -- VAR_MENO_OBB_RES_PRO
    NULL,  -- CDS_MAN
    NULL,  -- PG_MAN
    NULL,  -- DS_MANDATO
    0,  -- PAGATO_RES_PROPRIO
    0,  -- PAGATO_RES_IMPROPRIO
    DECODE(NVL(os.IM_ASSOCIATO_DOC_AMM, 0),
           0, 0,
           (osv.IM_VOCE / os.IM_SCADENZA) * os.IM_ASSOCIATO_DOC_AMM
    ),  -- IMP_DOC_RES_PROPRIO
    0  -- IMP_DOC_RES_IMPROPRIO
FROM obbligazione o
INNER JOIN obbligazione_scadenzario os
    ON os.CD_CDS = o.CD_CDS
    AND os.ESERCIZIO = o.ESERCIZIO
    AND os.ESERCIZIO_ORIGINALE = o.ESERCIZIO_ORIGINALE
    AND os.PG_OBBLIGAZIONE = o.PG_OBBLIGAZIONE
INNER JOIN obbligazione_scad_voce osv
    ON osv.CD_CDS = os.CD_CDS
    AND osv.ESERCIZIO = os.ESERCIZIO
    AND osv.ESERCIZIO_ORIGINALE = os.ESERCIZIO_ORIGINALE
    AND osv.PG_OBBLIGAZIONE = os.PG_OBBLIGAZIONE
    AND osv.PG_OBBLIGAZIONE_SCADENZARIO = os.PG_OBBLIGAZIONE_SCADENZARIO
LEFT OUTER JOIN elemento_voce ev
    ON o.ESERCIZIO = ev.ESERCIZIO
    AND o.CD_ELEMENTO_VOCE = ev.CD_ELEMENTO_VOCE
WHERE osv.IM_VOCE > 0  -- sf 16.03.2009 evita le righe a zero
AND o.CD_TIPO_DOCUMENTO_CONT IN ('OBB_RES', 'OBB_PGIR_R', 'IMP_RES')
AND o.PG_OBBLIGAZIONE > 0
AND NOT EXISTS (
    SELECT 1
    FROM mandato m
    INNER JOIN mandato_riga mr
        ON mr.CD_CDS = m.CD_CDS
        AND mr.ESERCIZIO = m.ESERCIZIO
        AND mr.PG_MANDATO = m.PG_MANDATO
    WHERE os.CD_CDS = mr.CD_CDS
    AND os.ESERCIZIO = mr.ESERCIZIO_OBBLIGAZIONE
    AND os.ESERCIZIO_ORIGINALE = mr.ESERCIZIO_ORI_OBBLIGAZIONE
    AND os.PG_OBBLIGAZIONE = mr.PG_OBBLIGAZIONE
    AND os.PG_OBBLIGAZIONE_SCADENZARIO = mr.PG_OBBLIGAZIONE_SCADENZARIO
    AND m.STATO != 'A'
)

UNION ALL

-- TERZA PARTE: MANDATI RESIDUI IMPROPRI
SELECT
    o.ESERCIZIO,
    o.ESERCIZIO_ORIGINALE,
    osv.CD_CENTRO_RESPONSABILITA,
    osv.CD_LINEA_ATTIVITA,
    o.TI_APPARTENENZA,
    o.TI_GESTIONE,
    o.CD_ELEMENTO_VOCE,
    ev.DS_ELEMENTO_VOCE,  -- JOIN con elemento_voce
    0,  -- IM_STANZ_RES_IMPROPRIO
    NULL,  -- PG_VAR_ST_RES
    NULL,  -- DS_VAR_ST_RES
    0,  -- VAR_PIU_ST_RES
    0,  -- VAR_MENO_ST_RES
    osv.CD_CDS,  -- CDS_OBB
    osv.PG_OBBLIGAZIONE,  -- PG_OBB
    o.DS_OBBLIGAZIONE,  -- DS_OBBLIGAZIONE
    osv.PG_OBBLIGAZIONE_SCADENZARIO,  -- PG_OBB_SCAD
    o.CD_TIPO_DOCUMENTO_CONT,
    os.DS_SCADENZA,
    0,  -- IM_OBBL_RES_IMP
    0,  -- IM_OBBL_RES_PRO
    NULL,  -- PG_VAR_RES_PRO
    NULL,  -- DS_VAR_RES_PRO
    0,  -- VAR_PIU_OBB_RES_PRO
    0,  -- VAR_MENO_OBB_RES_PRO
    NULL,  -- CDS_MAN
    NULL,  -- PG_MAN
    NULL,  -- DS_MANDATO
    0,  -- PAGATO_RES_PROPRIO
    0,  -- PAGATO_RES_IMPROPRIO
    0,  -- IMP_DOC_RES_PROPRIO
    DECODE(NVL(os.IM_ASSOCIATO_DOC_AMM, 0),
           0, 0,
           (osv.IM_VOCE / os.IM_SCADENZA) * os.IM_ASSOCIATO_DOC_AMM
    )  -- IMP_DOC_RES_IMPROPRIO
FROM obbligazione o
INNER JOIN obbligazione_scadenzario os
    ON os.CD_CDS = o.CD_CDS
    AND os.ESERCIZIO = o.ESERCIZIO
    AND os.ESERCIZIO_ORIGINALE = o.ESERCIZIO_ORIGINALE
    AND os.PG_OBBLIGAZIONE = o.PG_OBBLIGAZIONE
INNER JOIN obbligazione_scad_voce osv
    ON osv.CD_CDS = os.CD_CDS
    AND osv.ESERCIZIO = os.ESERCIZIO
    AND osv.ESERCIZIO_ORIGINALE = os.ESERCIZIO_ORIGINALE
    AND osv.PG_OBBLIGAZIONE = os.PG_OBBLIGAZIONE
    AND osv.PG_OBBLIGAZIONE_SCADENZARIO = os.PG_OBBLIGAZIONE_SCADENZARIO
LEFT OUTER JOIN elemento_voce ev
    ON o.ESERCIZIO = ev.ESERCIZIO
    AND o.CD_ELEMENTO_VOCE = ev.CD_ELEMENTO_VOCE
WHERE osv.IM_VOCE > 0  -- sf 16.03.2009 evita le righe a zero
AND o.CD_TIPO_DOCUMENTO_CONT IN ('OBB_RESIM')
AND o.PG_OBBLIGAZIONE > 0
AND NOT EXISTS (
    SELECT 1
    FROM mandato m
    INNER JOIN mandato_riga mr
        ON mr.CD_CDS = m.CD_CDS
        AND mr.ESERCIZIO = m.ESERCIZIO
        AND mr.PG_MANDATO = m.PG_MANDATO
    WHERE os.CD_CDS = mr.CD_CDS
    AND os.ESERCIZIO = mr.ESERCIZIO_OBBLIGAZIONE
    AND os.ESERCIZIO_ORIGINALE = mr.ESERCIZIO_ORI_OBBLIGAZIONE
    AND os.PG_OBBLIGAZIONE = mr.PG_OBBLIGAZIONE
    AND os.PG_OBBLIGAZIONE_SCADENZARIO = mr.PG_OBBLIGAZIONE_SCADENZARIO
    AND m.STATO != 'A'
);