--------------------------------------------------------
--  DDL for View V_COGE_COSTI_BY_COFI
--------------------------------------------------------
CREATE OR REPLACE FORCE EDITIONABLE VIEW "V_COGE_COSTI_BY_COFI" ("CD_TIPO_DOCUMENTO_AMM", "ESERCIZIO", "ESERCIZIO_DOCAMM", "CD_CDS", "CD_UNITA_ORGANIZZATIVA", "PG_DOCUMENTO_GENERICO", "CD_NUMERATORE_ORDINE", "RIGA_ORDINE", "CONSEGNA_ORDINE", "CD_VOCE_EP", "CD_ELEMENTO_VOCE", "TI_APPARTENENZA", "TI_GESTIONE", "IM_COFI", "IM_NO_COFI") AS
SELECT X.CD_TIPO_DOCUMENTO_AMM, X.ESERCIZIO, X.ESERCIZIO_DOCAMM, X.CD_CDS, X.CD_UNITA_ORGANIZZATIVA, X.PG_DOCUMENTO_GENERICO, X.CD_NUMERATORE_ORDINE, X.RIGA_ORDINE, X.CONSEGNA_ORDINE, X.CD_VOCE_EP, X.CD_ELEMENTO_VOCE, X.TI_APPARTENENZA, X.TI_GESTIONE, SUM(X.IM_COFI), SUM(X.IM_NO_COFI)
FROM (SELECT DG.CD_TIPO_DOCUMENTO_AMM, DG.ESERCIZIO, DG.ESERCIZIO ESERCIZIO_DOCAMM, DG.CD_CDS, DG.CD_UNITA_ORGANIZZATIVA, DG.PG_DOCUMENTO_GENERICO,
             NULL CD_NUMERATORE_ORDINE, NULL RIGA_ORDINE, NULL CONSEGNA_ORDINE,
             CASE
                 WHEN TO_CHAR(R.DT_A_COMPETENZA_COGE,'YYYY')<DG.ESERCIZIO
                     THEN 'P00047'
                 ELSE CASE WHEN R.CD_VOCE_EP IS NOT NULL
                               THEN R.CD_VOCE_EP
                           ELSE (SELECT aev.CD_VOCE_EP FROM ASS_EV_VOCEEP aev
                                 WHERE aev.ESERCIZIO = a.ESERCIZIO AND aev.TI_APPARTENENZA = a.TI_APPARTENENZA
                                   AND aev.TI_GESTIONE = a.TI_GESTIONE AND aev.CD_ELEMENTO_VOCE = a.CD_ELEMENTO_VOCE)
                     END
                 END CD_VOCE_EP,
             CD_ELEMENTO_VOCE,TI_APPARTENENZA, TI_GESTIONE,
             CASE WHEN B.IM_ASSOCIATO_DOC_AMM != 0 OR B.IM_SCADENZA = 0 THEN R.IM_RIGA ELSE 0 END
		 *
   		 CASE WHEN DG.FL_STORNO = 'Y' THEN -1 ELSE 1 END IM_COFI,
		 0 IM_NO_COFI
      FROM DOCUMENTO_GENERICO_RIGA R, OBBLIGAZIONE A, OBBLIGAZIONE_SCADENZARIO B, DOCUMENTO_GENERICO DG
      WHERE DG.CD_CDS = R.CD_CDS
        AND   DG.CD_UNITA_ORGANIZZATIVA = R.CD_UNITA_ORGANIZZATIVA
        AND   DG.CD_TIPO_DOCUMENTO_AMM = R.CD_TIPO_DOCUMENTO_AMM
        AND   DG.PG_DOCUMENTO_GENERICO = R.PG_DOCUMENTO_GENERICO
        AND   DG.ESERCIZIO = R.ESERCIZIO
        AND   R.CD_CDS_OBBLIGAZIONE = B.CD_CDS
        AND   R.ESERCIZIO_OBBLIGAZIONE = B.ESERCIZIO
        AND   R.ESERCIZIO_ORI_OBBLIGAZIONE = B.ESERCIZIO_ORIGINALE
        AND   R.PG_OBBLIGAZIONE = B.PG_OBBLIGAZIONE
        AND   R.PG_OBBLIGAZIONE_SCADENZARIO = B.PG_OBBLIGAZIONE_SCADENZARIO
        AND   A.CD_CDS = B.CD_CDS
        AND   A.ESERCIZIO = B.ESERCIZIO
        AND   A.ESERCIZIO_ORIGINALE = B.ESERCIZIO_ORIGINALE
        AND   A.PG_OBBLIGAZIONE = B.PG_OBBLIGAZIONE
        AND  (A.DT_CANCELLAZIONE IS NULL OR TRUNC(A.DT_CANCELLAZIONE) > TO_DATE('3112'||DG.ESERCIZIO,'DDMMYYYY'))
        AND  (DG.DT_CANCELLAZIONE IS NULL OR TRUNC(DG.DT_CANCELLAZIONE) > TO_DATE('3112'||DG.ESERCIZIO,'DDMMYYYY'))
        AND  (DG.CD_CAUSALE_CONTABILE IS NULL OR
          NOT EXISTS(SELECT '1' FROM ASS_CAUSALE_VOCE_EP C
          WHERE C.ESERCIZIO = DG.ESERCIZIO
        AND C.CD_CAUSALE = DG.CD_CAUSALE_CONTABILE
        AND C.TI_SEZIONE = 'D'))
      UNION ALL
      SELECT DG.CD_TIPO_DOCUMENTO_AMM, DG.ESERCIZIO, DG.ESERCIZIO, DG.CD_CDS, DG.CD_UNITA_ORGANIZZATIVA, DG.PG_DOCUMENTO_GENERICO,
          NULL CD_NUMERATORE_ORDINE, NULL RIGA_ORDINE, NULL CONSEGNA_ORDINE,
          CASE
          WHEN TO_CHAR(R.DT_A_COMPETENZA_COGE,'YYYY')<DG.ESERCIZIO
          THEN 'P00047'
          ELSE CASE WHEN R.CD_VOCE_EP IS NOT NULL
          THEN R.CD_VOCE_EP
          ELSE (SELECT C.CD_VOCE_EP FROM ASS_CAUSALE_VOCE_EP C
          WHERE C.ESERCIZIO = DG.ESERCIZIO
          AND C.CD_CAUSALE = DG.CD_CAUSALE_CONTABILE
          AND C.TI_SEZIONE = 'D')
          END
          END CD_VOCE_EP,
          CD_ELEMENTO_VOCE,TI_APPARTENENZA, TI_GESTIONE,
          CASE WHEN B.IM_ASSOCIATO_DOC_AMM != 0 OR B.IM_SCADENZA = 0 THEN R.IM_RIGA ELSE 0 END
          *
          CASE WHEN DG.FL_STORNO = 'Y' THEN -1 ELSE 1 END IM_COFI,
          0 IM_NO_COFI
      FROM DOCUMENTO_GENERICO_RIGA R, OBBLIGAZIONE A, OBBLIGAZIONE_SCADENZARIO B, DOCUMENTO_GENERICO DG
      WHERE DG.CD_CDS = R.CD_CDS
        AND   DG.CD_UNITA_ORGANIZZATIVA = R.CD_UNITA_ORGANIZZATIVA
        AND   DG.CD_TIPO_DOCUMENTO_AMM = R.CD_TIPO_DOCUMENTO_AMM
        AND   DG.PG_DOCUMENTO_GENERICO = R.PG_DOCUMENTO_GENERICO
        AND   DG.ESERCIZIO = R.ESERCIZIO
        AND   R.CD_CDS_OBBLIGAZIONE = B.CD_CDS
        AND   R.ESERCIZIO_OBBLIGAZIONE = B.ESERCIZIO
        AND   R.ESERCIZIO_ORI_OBBLIGAZIONE = B.ESERCIZIO_ORIGINALE
        AND   R.PG_OBBLIGAZIONE = B.PG_OBBLIGAZIONE
        AND   R.PG_OBBLIGAZIONE_SCADENZARIO = B.PG_OBBLIGAZIONE_SCADENZARIO
        AND   A.CD_CDS = B.CD_CDS
        AND   A.ESERCIZIO = B.ESERCIZIO
        AND   A.ESERCIZIO_ORIGINALE = B.ESERCIZIO_ORIGINALE
        AND   A.PG_OBBLIGAZIONE = B.PG_OBBLIGAZIONE
        AND  (A.DT_CANCELLAZIONE IS NULL OR TRUNC(A.DT_CANCELLAZIONE) > TO_DATE('3112'||DG.ESERCIZIO,'DDMMYYYY'))
        AND  (DG.DT_CANCELLAZIONE IS NULL OR TRUNC(DG.DT_CANCELLAZIONE) > TO_DATE('3112'||DG.ESERCIZIO,'DDMMYYYY'))
        AND   DG.CD_CAUSALE_CONTABILE IS NOT NULL
        AND   EXISTS(SELECT '1' FROM ASS_CAUSALE_VOCE_EP C
          WHERE C.ESERCIZIO = DG.ESERCIZIO
        AND C.CD_CAUSALE = DG.CD_CAUSALE_CONTABILE
        AND C.TI_SEZIONE = 'D')
      UNION ALL
      SELECT DISTINCT 'ORDINE_CNS', eor.ESERCIZIO, oac.ESERCIZIO, oac.CD_CDS, oac.CD_UNITA_OPERATIVA, oac.NUMERO,
          oac.CD_NUMERATORE, oac.RIGA, oac.CONSEGNA,
          CASE WHEN oac.CD_VOCE_EP IS NOT NULL
          THEN oac.CD_VOCE_EP
          ELSE CASE
          WHEN oac.PG_OBBLIGAZIONE IS NULL
          THEN 'C00066'
          ELSE CASE
          WHEN OAC.CD_VOCE_EP IS NOT NULL
          THEN OAC.CD_VOCE_EP
          ELSE (SELECT aev.CD_VOCE_EP FROM ASS_EV_VOCEEP aev
          WHERE aev.ESERCIZIO = a.ESERCIZIO AND aev.TI_APPARTENENZA = a.TI_APPARTENENZA
          AND aev.TI_GESTIONE = a.TI_GESTIONE AND aev.CD_ELEMENTO_VOCE = a.CD_ELEMENTO_VOCE)
          END
          END
          END CD_VOCE_EP,
          CD_ELEMENTO_VOCE,TI_APPARTENENZA, TI_GESTIONE,
          CASE WHEN oac.PG_OBBLIGAZIONE IS NOT NULL
          THEN CASE
          WHEN B.IM_ASSOCIATO_DOC_AMM != 0 OR B.IM_SCADENZA = 0
          THEN CASE WHEN oa.TI_ATTIVITA = 'C' THEN oac.IM_IMPONIBILE ELSE oac.IM_IMPONIBILE + oac.IM_IVA END
          ELSE 0
          END
          ELSE 0
          END IM_COFI,
          CASE WHEN oac.PG_OBBLIGAZIONE IS NULL
          THEN CASE WHEN oa.TI_ATTIVITA = 'C' THEN oac.IM_IMPONIBILE ELSE oac.IM_IMPONIBILE + oac.IM_IVA END
          ELSE 0
          END IM_NO_COFI
      FROM ORDINE_ACQ_CONSEGNA oac
          LEFT JOIN ORDINE_ACQ oa ON oa.CD_CDS = oac.CD_CDS AND oa.CD_UNITA_OPERATIVA = oac.CD_UNITA_OPERATIVA AND oa.ESERCIZIO = oac.ESERCIZIO AND
          oa.CD_NUMERATORE = oac.CD_NUMERATORE AND oa.NUMERO = oac.NUMERO
          LEFT OUTER JOIN OBBLIGAZIONE_SCADENZARIO B ON B.CD_CDS = oac.CD_CDS_OBBL AND B.ESERCIZIO = oac.ESERCIZIO_OBBL AND
          B.ESERCIZIO_ORIGINALE = oac.ESERCIZIO_ORIG_OBBL AND B.PG_OBBLIGAZIONE = oac.PG_OBBLIGAZIONE AND
          B.PG_OBBLIGAZIONE_SCADENZARIO = oac.PG_OBBLIGAZIONE_SCAD
          LEFT OUTER JOIN OBBLIGAZIONE A ON A.CD_CDS = B.CD_CDS	AND A.ESERCIZIO = B.ESERCIZIO AND A.ESERCIZIO_ORIGINALE = B.ESERCIZIO_ORIGINALE AND
          A.PG_OBBLIGAZIONE = B.PG_OBBLIGAZIONE
          LEFT JOIN EVASIONE_ORDINE_RIGA eor ON eor.CD_CDS_ORDINE = oac.CD_CDS AND eor.CD_UNITA_OPERATIVA = oac.CD_UNITA_OPERATIVA AND
          eor.ESERCIZIO_ORDINE = oac.ESERCIZIO AND eor.CD_NUMERATORE_ORDINE = oac.CD_NUMERATORE AND eor.NUMERO_ORDINE = oac.NUMERO and
          eor.RIGA_ORDINE = oac.RIGA AND eor.CONSEGNA = oac.CONSEGNA
          LEFT JOIN EVASIONE_ORDINE eo ON eo.CD_CDS = eor.CD_CDS AND eo.CD_MAGAZZINO = eor.CD_MAGAZZINO AND eo.ESERCIZIO = eor.ESERCIZIO AND
          eo.CD_NUMERATORE_MAG = eor.CD_NUMERATORE_MAG AND eo.NUMERO = eor.NUMERO
      WHERE oa.STATO != 'ANN'
        AND eo.STATO != 'ANN'
        AND eor.STATO != 'ANN'
        AND oac.STATO = 'EVA'
      UNION ALL
      SELECT 'FATTURA_P', FP.ESERCIZIO, FP.ESERCIZIO, FP.CD_CDS, FP.CD_UNITA_ORGANIZZATIVA, FP.PG_FATTURA_PASSIVA,
          NULL CD_NUMERATORE_ORDINE, NULL RIGA_ORDINE, NULL CONSEGNA_ORDINE,
          CASE
          WHEN NOT (FP.TI_FATTURA = 'C' AND R2.DT_A_COMPETENZA_COGE IS NOT NULL AND R2.ESERCIZIO < FP.ESERCIZIO) AND
          TO_CHAR(NVL(R2.DT_A_COMPETENZA_COGE, R.DT_A_COMPETENZA_COGE),'YYYY')<FP.ESERCIZIO
          THEN 'P00047'
          ELSE CASE WHEN R.CD_VOCE_EP IS NOT NULL
          THEN R.CD_VOCE_EP
          ELSE CASE
          WHEN R.PG_OBBLIGAZIONE IS NULL
          THEN 'C00066'
          ELSE CASE
          WHEN R.CD_VOCE_EP IS NOT NULL
          THEN R.CD_VOCE_EP
          ELSE (SELECT aev.CD_VOCE_EP FROM ASS_EV_VOCEEP aev
          WHERE aev.ESERCIZIO = a.ESERCIZIO AND aev.TI_APPARTENENZA = a.TI_APPARTENENZA
          AND aev.TI_GESTIONE = a.TI_GESTIONE AND aev.CD_ELEMENTO_VOCE = a.CD_ELEMENTO_VOCE)
          END
          END
          END
          END CD_VOCE_EP,
          CD_ELEMENTO_VOCE,TI_APPARTENENZA, TI_GESTIONE,
          CASE WHEN R.PG_OBBLIGAZIONE IS NOT NULL
          THEN CASE
          WHEN B.IM_ASSOCIATO_DOC_AMM != 0 OR B.IM_SCADENZA = 0 OR (FP.TI_FATTURA='C' AND nvl(B.IM_ASSOCIATO_DOC_AMM,0) = 0)
          THEN CASE WHEN FP.TI_ISTITUZ_COMMERC = 'C' THEN R.IM_IMPONIBILE ELSE R.IM_IMPONIBILE + R.IM_IVA END
          ELSE 0
          END
          *
          CASE WHEN FP.TI_FATTURA = 'C' THEN -1 ELSE 1 END
          ELSE 0
          END IM_COFI,
          CASE WHEN R.PG_OBBLIGAZIONE IS NULL
          THEN CASE WHEN FP.TI_ISTITUZ_COMMERC = 'C' THEN R.IM_IMPONIBILE ELSE R.IM_IMPONIBILE + R.IM_IVA END
          *
          CASE WHEN FP.TI_FATTURA = 'C' THEN -1 ELSE 1 END
          ELSE 0
          END IM_NO_COFI
      FROM FATTURA_PASSIVA_RIGA R
          LEFT JOIN FATTURA_PASSIVA FP ON FP.CD_CDS = R.CD_CDS AND FP.CD_UNITA_ORGANIZZATIVA = R.CD_UNITA_ORGANIZZATIVA AND
          FP.ESERCIZIO = R.ESERCIZIO AND FP.PG_FATTURA_PASSIVA = R.PG_FATTURA_PASSIVA
          LEFT JOIN OBBLIGAZIONE_SCADENZARIO B ON B.CD_CDS = R.CD_CDS_OBBLIGAZIONE AND B.ESERCIZIO = R.ESERCIZIO_OBBLIGAZIONE AND
          B.ESERCIZIO_ORIGINALE = R.ESERCIZIO_ORI_OBBLIGAZIONE AND B.PG_OBBLIGAZIONE = R.PG_OBBLIGAZIONE AND
          B.PG_OBBLIGAZIONE_SCADENZARIO = R.PG_OBBLIGAZIONE_SCADENZARIO
          LEFT JOIN OBBLIGAZIONE A ON A.CD_CDS = B.CD_CDS	AND A.ESERCIZIO = B.ESERCIZIO AND A.ESERCIZIO_ORIGINALE = B.ESERCIZIO_ORIGINALE AND
          A.PG_OBBLIGAZIONE = B.PG_OBBLIGAZIONE
          LEFT OUTER JOIN FATTURA_ORDINE FO ON FO.CD_CDS = R.CD_CDS AND FO.CD_UNITA_ORGANIZZATIVA = R.CD_UNITA_ORGANIZZATIVA AND
          FO.ESERCIZIO = R.ESERCIZIO AND FO.PG_FATTURA_PASSIVA = R.PG_FATTURA_PASSIVA AND FO.PROGRESSIVO_RIGA = R.PROGRESSIVO_RIGA
          LEFT OUTER JOIN FATTURA_PASSIVA_RIGA R2 ON R2.CD_CDS = R.CD_CDS_ASSNCNA_ECO AND R2.CD_UNITA_ORGANIZZATIVA = R.CD_UO_ASSNCNA_ECO AND
          R2.ESERCIZIO = R.ESERCIZIO_ASSNCNA_ECO AND R2.PG_FATTURA_PASSIVA = R.PG_FATTURA_ASSNCNA_ECO AND R2.PROGRESSIVO_RIGA = R.PG_RIGA_ASSNCNA_ECO
      WHERE FO.CD_CDS IS NULL
        AND   (A.DT_CANCELLAZIONE IS NULL OR TRUNC(A.DT_CANCELLAZIONE) > TO_DATE('3112'||FP.ESERCIZIO,'DDMMYYYY'))
        AND   (FP.DT_CANCELLAZIONE IS NULL OR TRUNC(FP.DT_CANCELLAZIONE) > TO_DATE('3112'||FP.ESERCIZIO,'DDMMYYYY'))
      UNION ALL
      SELECT 'COMPENSO', R.ESERCIZIO, R.ESERCIZIO, R.CD_CDS, R.CD_UNITA_ORGANIZZATIVA, R.PG_COMPENSO,
          NULL CD_NUMERATORE_ORDINE, NULL RIGA_ORDINE, NULL CONSEGNA_ORDINE,
          CASE
          WHEN R.CD_VOCE_EP IS NOT NULL
          THEN R.CD_VOCE_EP
          ELSE (SELECT aev.CD_VOCE_EP FROM ASS_EV_VOCEEP aev
          WHERE aev.ESERCIZIO = a.ESERCIZIO AND aev.TI_APPARTENENZA = a.TI_APPARTENENZA
          AND aev.TI_GESTIONE = a.TI_GESTIONE AND aev.CD_ELEMENTO_VOCE = a.CD_ELEMENTO_VOCE)
          END CD_VOCE_EP,
          CD_ELEMENTO_VOCE,TI_APPARTENENZA, TI_GESTIONE,
          CASE WHEN B.IM_ASSOCIATO_DOC_AMM != 0 OR B.IM_SCADENZA = 0 THEN R.IM_TOTALE_COMPENSO ELSE 0 END IM_COFI,
          0 IM_NO_COFI
      FROM COMPENSO R, OBBLIGAZIONE A, OBBLIGAZIONE_SCADENZARIO B
      WHERE R.CD_CDS_OBBLIGAZIONE = B.CD_CDS
        AND   R.ESERCIZIO_OBBLIGAZIONE = B.ESERCIZIO
        AND   R.ESERCIZIO_ORI_OBBLIGAZIONE = B.ESERCIZIO_ORIGINALE
        AND   R.PG_OBBLIGAZIONE = B.PG_OBBLIGAZIONE
        AND   R.PG_OBBLIGAZIONE_SCADENZARIO = B.PG_OBBLIGAZIONE_SCADENZARIO
        AND   A.CD_CDS = B.CD_CDS
        AND   A.ESERCIZIO = B.ESERCIZIO
        AND   A.ESERCIZIO_ORIGINALE = B.ESERCIZIO_ORIGINALE
        AND   A.PG_OBBLIGAZIONE = B.PG_OBBLIGAZIONE
        AND   (A.DT_CANCELLAZIONE IS NULL OR TRUNC(A.DT_CANCELLAZIONE) > TO_DATE('3112'||R.ESERCIZIO,'DDMMYYYY'))
        AND   (R.DT_CANCELLAZIONE IS NULL OR TRUNC(R.DT_CANCELLAZIONE) > TO_DATE('3112'||R.ESERCIZIO,'DDMMYYYY'))) X
GROUP BY X.CD_TIPO_DOCUMENTO_AMM, X.ESERCIZIO, X.ESERCIZIO_DOCAMM, X.CD_CDS, X.CD_UNITA_ORGANIZZATIVA, X.PG_DOCUMENTO_GENERICO, X.CD_NUMERATORE_ORDINE, X.RIGA_ORDINE, X.CONSEGNA_ORDINE, X.CD_VOCE_EP, X.CD_ELEMENTO_VOCE, X.TI_APPARTENENZA, X.TI_GESTIONE;