<%@ page pageEncoding="UTF-8"
	import="it.cnr.jada.util.jsp.*,
		it.cnr.jada.action.*,
		java.util.*,
		it.cnr.jada.util.action.*,
		it.cnr.contab.docamm00.tabrif.bulk.*,
		it.cnr.contab.docamm00.docs.bulk.*,
		it.cnr.contab.docamm00.bp.*,
		it.cnr.contab.anagraf00.tabrif.bulk.*"
%>

<% CRUDFatturaPassivaBP bp = (CRUDFatturaPassivaBP)BusinessProcess.getBusinessProcess(request);
	Fattura_passivaBulk fatturaPassiva = (Fattura_passivaBulk)bp.getModel();
	boolean roOnAutoGen = false;
	if (bp instanceof IDocumentoAmministrativoBP)
		roOnAutoGen = ((IDocumentoAmministrativoBP)bp).isAutoGenerated();
	if (fatturaPassiva instanceof Fattura_passiva_IBulk)
		bp.getDettaglio().writeHTMLTable(pageContext,"righiSet",true,false,true,"100%","auto;max-height:40vh");
	else if (fatturaPassiva instanceof Nota_di_creditoBulk)
		bp.getDettaglio().writeHTMLTable(pageContext,"righeNdCSet",true,false,true,"100%","auto;max-height:40vh");
	else 
		bp.getDettaglio().writeHTMLTable(pageContext,"righeNdDSet",true,false,true,"100%","auto;max-height:40vh"); %>

<% if (bp.isAttivaEconomica() || bp.isAttivaAnalitica()) {
  JSPUtils.tabbed(
				pageContext,
				"tabFatturaPassivaDettaglio",
				new String[][] {
						{ "tabFatturaPassivaDettaglioDetail1","Dettaglio","/docamm00/tab_fattura_passiva_dettaglio_detail.jsp" },
						{ "tabFatturaPassivaDettaglioDetail2","Dati Coge/Coan","/coepcoan00/tab_doc_detail_eco_coge.jsp" } },
				bp.getTab("tabFatturaPassivaDettaglio"),
				"center",
				"100%",
				null);
 } else { %>
<jsp:include page="/docamm00/tab_fattura_passiva_dettaglio_detail.jsp" />
<% } %>