--------------------------------------------------------
--  DDL for View V_CONS_REGISTRO_INVENTARIO
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "V_CONS_REGISTRO_INVENTARIO" ("PG_INVENTARIO", "TI_DOCUMENTO", "ESERCIZIO", "PG_BUONO_C_S", "NR_INVENTARIO", "PROGRESSIVO", "CD_UNITA_ORGANIZZATIVA", "CD_CDS", "ESERCIZIO_CARICO_BENE", "ETICHETTA", "DS_BENE", "VALORE_INIZIALE", "CATEGORIA", "CD_CATEGORIA_GRUPPO", "DS_CATEGORIA_GRUPPO", "DS_UBICAZIONE_BENE", "CD_ASSEGNATARIO", "DENOMINAZIONE_SEDE", "DATA_REGISTRAZIONE", "CD_TIPO_CARICO_SCARICO", "DS_TIPO_CARICO_SCARICO", "VARIAZIONE_PIU", "VARIAZIONE_MENO", "QUANTITA", "VALORE_UNITARIO", "IMPONIBILE_AMMORTAMENTO", "VALORE_AMMORTIZZATO", "IM_MOVIMENTO_AMMORT", "NUMERO_ANNI", "PERC_AMMORTAMENTO", "PERC_PRIMO_ANNO", "PERC_SUCCESSIVI", "CD_UTILIZZATORE_CDR", "CD_LINEA_ATTIVITA", "PERCENTUALE_UTILIZZO_CDR", "PERCENTUALE_UTILIZZO_LA", "ESERCIZIO_AMM") AS
  SELECT
BUONO_CARICO_SCARICO_DETT.PG_INVENTARIO,
BUONO_CARICO_SCARICO_DETT.TI_DOCUMENTO,
BUONO_CARICO_SCARICO_DETT.ESERCIZIO,
BUONO_CARICO_SCARICO_DETT.PG_BUONO_C_S,
BUONO_CARICO_SCARICO_DETT.NR_INVENTARIO,
BUONO_CARICO_SCARICO_DETT.PROGRESSIVO,
INVENTARIO_BENI.CD_UNITA_ORGANIZZATIVA,
INVENTARIO_BENI.CD_CDS,
INVENTARIO_BENI.ESERCIZIO_CARICO_BENE,
INVENTARIO_BENI.ETICHETTA,
INVENTARIO_BENI.DS_BENE,
DECODE(BUONO_CARICO_SCARICO_DETT.TI_DOCUMENTO,'C',DECODE(BUONO_CARICO_SCARICO_DETT.PG_BUONO_C_S,(SELECT MIN(dett.PG_BUONO_C_S)
                                    FROM BUONO_CARICO_SCARICO_DETT dett
                                    WHERE dett.TI_DOCUMENTO = 'C'
				      AND dett.PG_INVENTARIO = INVENTARIO_BENI.PG_INVENTARIO
                                      AND dett.NR_INVENTARIO = INVENTARIO_BENI.NR_INVENTARIO
                                      AND dett.PROGRESSIVO   = INVENTARIO_BENI.PROGRESSIVO
                                      AND dett.ESERCIZIO = BUONO_CARICO_SCARICO_DETT.ESERCIZIO
                                      AND dett.ESERCIZIO = (SELECT MIN(dett2.ESERCIZIO)
                                                            FROM BUONO_CARICO_SCARICO_DETT dett2
                                                            WHERE dett2.PG_INVENTARIO = dett.PG_INVENTARIO
                                                              AND dett2.NR_INVENTARIO = dett.NR_INVENTARIO
                                                              AND dett2.PROGRESSIVO   = dett.PROGRESSIVO
                                                              AND dett2.TI_DOCUMENTO  = dett.TI_DOCUMENTO)),
                             BUONO_CARICO_SCARICO_DETT.VALORE_UNITARIO,0),0) VALORE_INIZIALE,
cd_categoria_padre CATEGORIA,
INVENTARIO_BENI.CD_CATEGORIA_GRUPPO,
CATEGORIA_GRUPPO_INVENT.DS_CATEGORIA_GRUPPO,
UBICAZIONE_BENE.DS_UBICAZIONE_BENE,
INVENTARIO_BENI.CD_ASSEGNATARIO,
TERZO.DENOMINAZIONE_SEDE,
BUONO_CARICO_SCARICO.DATA_REGISTRAZIONE,
TIPO_CARICO_SCARICO.CD_TIPO_CARICO_SCARICO,
TIPO_CARICO_SCARICO.DS_TIPO_CARICO_SCARICO,
DECODE(BUONO_CARICO_SCARICO_DETT.PG_BUONO_C_S,(SELECT MIN(dett.PG_BUONO_C_S)
                                    FROM BUONO_CARICO_SCARICO_DETT dett
                                    WHERE dett.TI_DOCUMENTO = 'C'
				      AND dett.PG_INVENTARIO = INVENTARIO_BENI.PG_INVENTARIO
                                      AND dett.NR_INVENTARIO = INVENTARIO_BENI.NR_INVENTARIO
                                      AND dett.PROGRESSIVO   = INVENTARIO_BENI.PROGRESSIVO
                                      AND dett.ESERCIZIO = BUONO_CARICO_SCARICO_DETT.ESERCIZIO
                                      AND dett.ESERCIZIO = (SELECT MIN(dett2.ESERCIZIO)
                                                            FROM BUONO_CARICO_SCARICO_DETT dett2
                                                            WHERE dett2.PG_INVENTARIO = dett.PG_INVENTARIO
                                                              AND dett2.NR_INVENTARIO = dett.NR_INVENTARIO
                                                              AND dett2.PROGRESSIVO   = dett.PROGRESSIVO
                                                              AND dett2.TI_DOCUMENTO  = dett.TI_DOCUMENTO)),0,
		DECODE(BUONO_CARICO_SCARICO_DETT.TI_DOCUMENTO,'C',BUONO_CARICO_SCARICO_DETT.VALORE_UNITARIO,0)) VARIAZIONE_PIU,
                DECODE(BUONO_CARICO_SCARICO_DETT.TI_DOCUMENTO,'S',BUONO_CARICO_SCARICO_DETT.VALORE_UNITARIO,0) VARIAZIONE_MENO,
BUONO_CARICO_SCARICO_DETT.QUANTITA,
BUONO_CARICO_SCARICO_DETT.VALORE_UNITARIO,
Nvl(INVENTARIO_BENI.IMPONIBILE_AMMORTAMENTO,0),
INVENTARIO_BENI.VALORE_AMMORTIZZATO,
(Nvl(AMMORTAMENTO_BENE_INV.IM_MOVIMENTO_AMMORT,0)*Nvl(INVENTARIO_UTILIZZATORI_LA.PERCENTUALE_UTILIZZO_CDR,100)/100 * Nvl(INVENTARIO_UTILIZZATORI_LA.PERCENTUALE_UTILIZZO_LA,100)/100)IM_MOVIMENTO_AMMORT,
AMMORTAMENTO_BENE_INV.NUMERO_ANNI,
AMMORTAMENTO_BENE_INV.PERC_AMMORTAMENTO,
AMMORTAMENTO_BENE_INV.PERC_PRIMO_ANNO,
AMMORTAMENTO_BENE_INV.PERC_SUCCESSIVI,
INVENTARIO_UTILIZZATORI_LA.CD_UTILIZZATORE_CDR,
INVENTARIO_UTILIZZATORI_LA.CD_LINEA_ATTIVITA,
INVENTARIO_UTILIZZATORI_LA.PERCENTUALE_UTILIZZO_CDR,
INVENTARIO_UTILIZZATORI_LA.PERCENTUALE_UTILIZZO_LA,
AMMORTAMENTO_BENE_INV.ESERCIZIO
FROM
INVENTARIO_BENI
INNER JOIN UBICAZIONE_BENE ON UBICAZIONE_BENE.CD_CDS = INVENTARIO_BENI.CD_CDS
	AND UBICAZIONE_BENE.CD_UNITA_ORGANIZZATIVA = INVENTARIO_BENI.CD_UNITA_ORGANIZZATIVA
	AND UBICAZIONE_BENE.CD_UBICAZIONE = INVENTARIO_BENI.CD_UBICAZIONE
INNER JOIN CATEGORIA_GRUPPO_INVENT ON CATEGORIA_GRUPPO_INVENT.CD_CATEGORIA_GRUPPO = INVENTARIO_BENI.CD_CATEGORIA_GRUPPO
INNER JOIN BUONO_CARICO_SCARICO_DETT ON BUONO_CARICO_SCARICO_DETT.PG_INVENTARIO = INVENTARIO_BENI.PG_INVENTARIO
	AND BUONO_CARICO_SCARICO_DETT.NR_INVENTARIO = INVENTARIO_BENI.NR_INVENTARIO
	AND BUONO_CARICO_SCARICO_DETT.PROGRESSIVO = INVENTARIO_BENI.PROGRESSIVO
INNER JOIN BUONO_CARICO_SCARICO ON BUONO_CARICO_SCARICO.PG_INVENTARIO = BUONO_CARICO_SCARICO_DETT.PG_INVENTARIO
	AND BUONO_CARICO_SCARICO.TI_DOCUMENTO = BUONO_CARICO_SCARICO_DETT.TI_DOCUMENTO
	AND BUONO_CARICO_SCARICO.ESERCIZIO = BUONO_CARICO_SCARICO_DETT.ESERCIZIO
	AND BUONO_CARICO_SCARICO.PG_BUONO_C_S = BUONO_CARICO_SCARICO_DETT.PG_BUONO_C_S
INNER JOIN TIPO_CARICO_SCARICO ON TIPO_CARICO_SCARICO.CD_TIPO_CARICO_SCARICO = BUONO_CARICO_SCARICO.CD_TIPO_CARICO_SCARICO
INNER JOIN TERZO ON TERZO.CD_UNITA_ORGANIZZATIVA = INVENTARIO_BENI.CD_UNITA_ORGANIZZATIVA
LEFT OUTER JOIN AMMORTAMENTO_BENE_INV ON AMMORTAMENTO_BENE_INV.PG_INVENTARIO = INVENTARIO_BENI.PG_INVENTARIO
	AND AMMORTAMENTO_BENE_INV.NR_INVENTARIO = INVENTARIO_BENI.NR_INVENTARIO
	AND AMMORTAMENTO_BENE_INV.PROGRESSIVO = INVENTARIO_BENI.PROGRESSIVO
LEFT OUTER JOIN INVENTARIO_UTILIZZATORI_LA ON INVENTARIO_UTILIZZATORI_LA.PG_INVENTARIO = INVENTARIO_BENI.PG_INVENTARIO
	AND INVENTARIO_UTILIZZATORI_LA.NR_INVENTARIO = INVENTARIO_BENI.NR_INVENTARIO
	AND INVENTARIO_UTILIZZATORI_LA.PROGRESSIVO = INVENTARIO_BENI.PROGRESSIVO;