--------------------------------------------------------
--  DDL for View V_COGE_COSTI_BY_COFI
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "V_COGE_COSTI_BY_COFI" ("CD_TIPO_DOCUMENTO_AMM", "ESERCIZIO", "CD_CDS", "CD_UNITA_ORGANIZZATIVA", "PG_DOCUMENTO_GENERICO", "CD_VOCE_EP", "CD_ELEMENTO_VOCE", "TI_APPARTENENZA", "TI_GESTIONE","IM_COFI") AS
  SELECT DG.CD_TIPO_DOCUMENTO_AMM, DG.ESERCIZIO, DG.CD_CDS, DG.CD_UNITA_ORGANIZZATIVA, DG.PG_DOCUMENTO_GENERICO,
		    (SELECT aev.CD_VOCE_EP FROM ASS_EV_VOCEEP aev
			   WHERE aev.ESERCIZIO = a.ESERCIZIO AND aev.TI_APPARTENENZA = a.TI_APPARTENENZA
			   AND aev.TI_GESTIONE = a.TI_GESTIONE AND aev.CD_ELEMENTO_VOCE = a.CD_ELEMENTO_VOCE) CD_VOCE_EP,
			   CD_ELEMENTO_VOCE,TI_APPARTENENZA, TI_GESTIONE,
		     CASE WHEN B.IM_ASSOCIATO_DOC_AMM != 0 OR B.IM_SCADENZA = 0 THEN R.IM_RIGA ELSE 0 END IM_COFI
	FROM DOCUMENTO_GENERICO_RIGA R, OBBLIGAZIONE A, OBBLIGAZIONE_SCADENZARIO B, DOCUMENTO_GENERICO DG
	WHERE DG.CD_CDS = R.CD_CDS
	AND   DG.CD_UNITA_ORGANIZZATIVA = R.CD_UNITA_ORGANIZZATIVA
	AND   DG.CD_TIPO_DOCUMENTO_AMM = R.CD_TIPO_DOCUMENTO_AMM
	AND   DG.PG_DOCUMENTO_GENERICO = R.PG_DOCUMENTO_GENERICO
	AND   DG.ESERCIZIO = R.ESERCIZIO
	AND   R.CD_CDS_OBBLIGAZIONE = B.CD_CDS
	AND   R.ESERCIZIO_OBBLIGAZIONE = B.ESERCIZIO
	AND   R.ESERCIZIO_ORI_OBBLIGAZIONE = B.ESERCIZIO_ORIGINALE
	AND   R.PG_OBBLIGAZIONE = B.PG_OBBLIGAZIONE
	AND   R.PG_OBBLIGAZIONE_SCADENZARIO = B.PG_OBBLIGAZIONE_SCADENZARIO
	AND   A.CD_CDS = B.CD_CDS
	AND   A.ESERCIZIO = B.ESERCIZIO
	AND   A.ESERCIZIO_ORIGINALE = B.ESERCIZIO_ORIGINALE
	AND   A.PG_OBBLIGAZIONE = B.PG_OBBLIGAZIONE
	AND  (A.DT_CANCELLAZIONE IS NULL OR TRUNC(A.DT_CANCELLAZIONE) > TO_DATE('3112'||DG.ESERCIZIO,'DDMMYYYY'))
	AND  (DG.DT_CANCELLAZIONE IS NULL OR TRUNC(DG.DT_CANCELLAZIONE) > TO_DATE('3112'||DG.ESERCIZIO,'DDMMYYYY'))
	UNION ALL
	SELECT 'FATTURA_P', FP.ESERCIZIO, FP.CD_CDS, FP.CD_UNITA_ORGANIZZATIVA, FP.PG_FATTURA_PASSIVA,
	       CASE
		   WHEN TO_CHAR(R.DT_A_COMPETENZA_COGE,'YYYY')<FP.ESERCIZIO
	       THEN 'P00047'
	       ELSE CASE
	            WHEN R.PG_OBBLIGAZIONE IS NULL
	            THEN 'C00066'
	            ELSE CASE
	            	 WHEN OAC.CD_VOCE_EP IS NOT NULL
	                 THEN OAC.CD_VOCE_EP
	                 ELSE (SELECT aev.CD_VOCE_EP FROM ASS_EV_VOCEEP aev
		                   WHERE aev.ESERCIZIO = a.ESERCIZIO AND aev.TI_APPARTENENZA = a.TI_APPARTENENZA
		                   AND aev.TI_GESTIONE = a.TI_GESTIONE AND aev.CD_ELEMENTO_VOCE = a.CD_ELEMENTO_VOCE)
		             END
		        END
		   END CD_VOCE_EP, CD_ELEMENTO_VOCE,TI_APPARTENENZA, TI_GESTIONE,
	       CASE WHEN B.IM_ASSOCIATO_DOC_AMM != 0 OR B.IM_SCADENZA = 0 THEN R.IM_IMPONIBILE + R.IM_IVA ELSE 0 END
		   *
           CASE WHEN FP.TI_FATTURA = 'F' THEN 1 ELSE -1 END IM_COFI
	FROM FATTURA_PASSIVA_RIGA R, OBBLIGAZIONE A, OBBLIGAZIONE_SCADENZARIO B, FATTURA_PASSIVA FP, FATTURA_ORDINE FO, ORDINE_ACQ_CONSEGNA OAC
	WHERE FP.CD_CDS = R.CD_CDS
	AND   FP.CD_UNITA_ORGANIZZATIVA = R.CD_UNITA_ORGANIZZATIVA
	AND   FP.ESERCIZIO = R.ESERCIZIO
	AND   FP.PG_FATTURA_PASSIVA = R.PG_FATTURA_PASSIVA
	AND   R.CD_CDS_OBBLIGAZIONE = B.CD_CDS
	AND   R.ESERCIZIO_OBBLIGAZIONE = B.ESERCIZIO
	AND   R.ESERCIZIO_ORI_OBBLIGAZIONE = B.ESERCIZIO_ORIGINALE
	AND   R.PG_OBBLIGAZIONE = B.PG_OBBLIGAZIONE
	AND   R.PG_OBBLIGAZIONE_SCADENZARIO = B.PG_OBBLIGAZIONE_SCADENZARIO
	AND   A.CD_CDS = B.CD_CDS
	AND   A.ESERCIZIO = B.ESERCIZIO
	AND   A.ESERCIZIO_ORIGINALE = B.ESERCIZIO_ORIGINALE
	AND   A.PG_OBBLIGAZIONE = B.PG_OBBLIGAZIONE
	AND   R.CD_CDS = FO.CD_CDS(+)
	AND   R.CD_UNITA_ORGANIZZATIVA = FO.CD_UNITA_ORGANIZZATIVA(+)
	AND   R.ESERCIZIO = FO.ESERCIZIO(+)
	AND   R.PG_FATTURA_PASSIVA = FO.PG_FATTURA_PASSIVA(+)
	AND   R.PROGRESSIVO_RIGA = FO.PROGRESSIVO_RIGA(+)
	AND   FO.CD_CDS_ORDINE = OAC.CD_CDS(+)
	AND   FO.CD_UNITA_OPERATIVA = OAC.CD_UNITA_OPERATIVA(+)
	AND   FO.ESERCIZIO_ORDINE = OAC.ESERCIZIO(+)
	AND   FO.CD_NUMERATORE = OAC.CD_NUMERATORE(+)
	AND   FO.NUMERO = OAC.NUMERO(+)
	AND   FO.RIGA = OAC.RIGA(+)
	AND   FO.CONSEGNA = OAC.CONSEGNA(+)
	AND   (A.DT_CANCELLAZIONE IS NULL OR TRUNC(A.DT_CANCELLAZIONE) > TO_DATE('3112'||FP.ESERCIZIO,'DDMMYYYY'))
	AND   (FP.DT_CANCELLAZIONE IS NULL OR TRUNC(FP.DT_CANCELLAZIONE) > TO_DATE('3112'||FP.ESERCIZIO,'DDMMYYYY'))
	UNION ALL
	SELECT 'COMPENSO', R.ESERCIZIO, R.CD_CDS, R.CD_UNITA_ORGANIZZATIVA, R.PG_COMPENSO,
	       (SELECT aev.CD_VOCE_EP FROM ASS_EV_VOCEEP aev
		    WHERE aev.ESERCIZIO = a.ESERCIZIO AND aev.TI_APPARTENENZA = a.TI_APPARTENENZA
		    AND aev.TI_GESTIONE = a.TI_GESTIONE AND aev.CD_ELEMENTO_VOCE = a.CD_ELEMENTO_VOCE) CD_VOCE_EP,
		    CD_ELEMENTO_VOCE,TI_APPARTENENZA, TI_GESTIONE,
           CASE WHEN B.IM_ASSOCIATO_DOC_AMM != 0 OR B.IM_SCADENZA = 0 THEN R.IM_TOTALE_COMPENSO ELSE 0 END IM_COFI
	FROM COMPENSO R, OBBLIGAZIONE A, OBBLIGAZIONE_SCADENZARIO B
	WHERE R.CD_CDS_OBBLIGAZIONE = B.CD_CDS
	AND   R.ESERCIZIO_OBBLIGAZIONE = B.ESERCIZIO
	AND   R.ESERCIZIO_ORI_OBBLIGAZIONE = B.ESERCIZIO_ORIGINALE
	AND   R.PG_OBBLIGAZIONE = B.PG_OBBLIGAZIONE
	AND   R.PG_OBBLIGAZIONE_SCADENZARIO = B.PG_OBBLIGAZIONE_SCADENZARIO
	AND   A.CD_CDS = B.CD_CDS
	AND   A.ESERCIZIO = B.ESERCIZIO
	AND   A.ESERCIZIO_ORIGINALE = B.ESERCIZIO_ORIGINALE
	AND   A.PG_OBBLIGAZIONE = B.PG_OBBLIGAZIONE
	AND   (A.DT_CANCELLAZIONE IS NULL OR TRUNC(A.DT_CANCELLAZIONE) > TO_DATE('3112'||R.ESERCIZIO,'DDMMYYYY'))
	AND   (R.DT_CANCELLAZIONE IS NULL OR TRUNC(R.DT_CANCELLAZIONE) > TO_DATE('3112'||R.ESERCIZIO,'DDMMYYYY'));
