--------------------------------------------------------
--  DDL for View CONFRONTA_COSTI_COGE_COFI
--------------------------------------------------------
CREATE OR REPLACE  VIEW "V_CONFRONTA_COSTI_COGE_COFI" ("ESERCIZIO", "VOCE_COGE", "VOCE_COFI", "IMPORTO_COGE", "IMPORTO_COFI") AS
  SELECT X.ESERCIZIO, X.VOCE_COGE, X.VOCE_COFI, SUM(X.IMPORTO_COGE) IMPORTO_COGE, SUM(X.IMPORTO_COFI) IMPORTO_COFI
FROM (SELECT A.ESERCIZIO, A.CD_VOCE_EP VOCE_COGE, 'TOTALE' VOCE_COFI, DECODE(A.SEZIONE, 'D', A.IM_MOVIMENTO, -A.IM_MOVIMENTO) IMPORTO_COGE, 0 IMPORTO_COFI
      FROM MOVIMENTO_COGE A
	  LEFT JOIN SCRITTURA_PARTITA_DOPPIA B ON B.ESERCIZIO=A.ESERCIZIO AND B.CD_CDS = A.CD_CDS AND B.CD_UNITA_ORGANIZZATIVA =  A.CD_UNITA_ORGANIZZATIVA AND B.PG_SCRITTURA = A.PG_SCRITTURA
	  WHERE B.ATTIVA = 'Y'
	  UNION ALL
	  SELECT A.ESERCIZIO, A.CD_VOCE_EP, A.CD_ELEMENTO_VOCE, 0, A.IM_COFI
	  FROM V_COGE_COSTI_BY_COFI A
	  UNION ALL
	  SELECT A.ESERCIZIO, A.CD_VOCE_EP, 'TOTALE', 0, SUM(A.IM_COFI)
	  FROM V_COGE_COSTI_BY_COFI A
	  GROUP BY A.ESERCIZIO, A.CD_VOCE_EP, 'TOTALE', 0) X
WHERE X.VOCE_COGE LIKE 'C%'
GROUP BY X.ESERCIZIO, X.VOCE_COGE, X.VOCE_COFI;
