--------------------------------------------------------
--  DDL for View V_CONS_SCAD_OBBL
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "V_CONS_SCAD_OBBL_ANNO_CORRENTE" (
         "CDS",
         "UO",
         "ESERCIZIO",
         "ESERCIZIO_ORIGINALE",
         "PG_OBBL",
         "PG_OBBL_SCAD",
         "VOCE_BILANCIO",
         "DATA_SCAD",
         "DS_OBBL",
         "DS_SCAD",
         "IM_SCAD",
         "IM_ASS_DOC_AMM",
         "IMP_ASS_DOC_CONT",
         "IMP_ORDINE",
         "IMP_EVASO",
         "IMP_ASS_FATTURA",
         "IMP_ASS_DOC_AMM",
         "CREDITORE",
         "DS_ELEMENTO_VOCE"
) AS SELECT DISTINCT
--
-- Date: 07/03/2007
-- Version: 1.0
--
-- Vista per la consultazione Scadenzario Impegni
--
--
-- Body
--
OBBLIGAZIONE_SCADENZARIO.CD_CDS,
OBBLIGAZIONE.CD_UNITA_ORGANIZZATIVA,
OBBLIGAZIONE_SCADENZARIO.ESERCIZIO,
OBBLIGAZIONE_SCADENZARIO.ESERCIZIO_ORIGINALE,
OBBLIGAZIONE_SCADENZARIO.PG_OBBLIGAZIONE,
OBBLIGAZIONE_SCADENZARIO.PG_OBBLIGAZIONE_SCADENZARIO,
OBBLIGAZIONE.CD_ELEMENTO_VOCE,
OBBLIGAZIONE_SCADENZARIO.DT_SCADENZA,
obbligazione.DS_OBBLIGAZIONE,
OBBLIGAZIONE_SCADENZARIO.DS_SCADENZA,
OBBLIGAZIONE_SCADENZARIO.IM_SCADENZA,
OBBLIGAZIONE_SCADENZARIO.IM_ASSOCIATO_DOC_AMM,
OBBLIGAZIONE_SCADENZARIO.IM_ASSOCIATO_DOC_CONTABILE,
NVL((
    SELECT SUM(IM_TOTALE_CONSEGNA)
    FROM ORDINE_ACQ_CONSEGNA
    WHERE ORDINE_ACQ_CONSEGNA.CD_CDS_OBBL = OBBLIGAZIONE_SCADENZARIO.CD_CDS
      --AND ORDINE_ACQ_CONSEGNA.ESERCIZIO_OBBL = OBBLIGAZIONE_SCADENZARIO.ESERCIZIO
      AND ORDINE_ACQ_CONSEGNA.ESERCIZIO <= OBBLIGAZIONE_SCADENZARIO.ESERCIZIO
      AND ORDINE_ACQ_CONSEGNA.ESERCIZIO_ORIG_OBBL = OBBLIGAZIONE_SCADENZARIO.ESERCIZIO_ORIGINALE
      AND ORDINE_ACQ_CONSEGNA.PG_OBBLIGAZIONE = OBBLIGAZIONE_SCADENZARIO.PG_OBBLIGAZIONE
      AND ORDINE_ACQ_CONSEGNA.PG_OBBLIGAZIONE_SCAD = OBBLIGAZIONE_SCADENZARIO.PG_OBBLIGAZIONE_SCADENZARIO
      AND ORDINE_ACQ_CONSEGNA.STATO != 'EVF'
    ),0) IMP_ORDINE,
NVL((
        SELECT SUM(IM_TOTALE_CONSEGNA)
        FROM ORDINE_ACQ_CONSEGNA
        WHERE ORDINE_ACQ_CONSEGNA.CD_CDS_OBBL = OBBLIGAZIONE_SCADENZARIO.CD_CDS
          --AND ORDINE_ACQ_CONSEGNA.ESERCIZIO_OBBL = OBBLIGAZIONE_SCADENZARIO.ESERCIZIO
          AND ORDINE_ACQ_CONSEGNA.ESERCIZIO <= OBBLIGAZIONE_SCADENZARIO.ESERCIZIO
          AND ORDINE_ACQ_CONSEGNA.ESERCIZIO_ORIG_OBBL = OBBLIGAZIONE_SCADENZARIO.ESERCIZIO_ORIGINALE
          AND ORDINE_ACQ_CONSEGNA.PG_OBBLIGAZIONE = OBBLIGAZIONE_SCADENZARIO.PG_OBBLIGAZIONE
          AND ORDINE_ACQ_CONSEGNA.PG_OBBLIGAZIONE_SCAD = OBBLIGAZIONE_SCADENZARIO.PG_OBBLIGAZIONE_SCADENZARIO
          AND ORDINE_ACQ_CONSEGNA.STATO = 'EVA'
    ),0) IMP_EVASO,
NVL((
        SELECT SUM(IM_TOTALE_DOC_AMM)
        FROM V_DOC_PASSIVO_OBBLIGAZIONE
        WHERE V_DOC_PASSIVO_OBBLIGAZIONE.CD_CDS_OBBLIGAZIONE = OBBLIGAZIONE_SCADENZARIO.CD_CDS
          --AND V_DOC_PASSIVO_OBBLIGAZIONE.ESERCIZIO_OBBLIGAZIONE = OBBLIGAZIONE_SCADENZARIO.ESERCIZIO
          AND V_DOC_PASSIVO_OBBLIGAZIONE.ESERCIZIO <= OBBLIGAZIONE_SCADENZARIO.ESERCIZIO
          AND V_DOC_PASSIVO_OBBLIGAZIONE.ESERCIZIO_ORI_OBBLIGAZIONE = OBBLIGAZIONE_SCADENZARIO.ESERCIZIO_ORIGINALE
          AND V_DOC_PASSIVO_OBBLIGAZIONE.PG_OBBLIGAZIONE = OBBLIGAZIONE_SCADENZARIO.PG_OBBLIGAZIONE
          AND V_DOC_PASSIVO_OBBLIGAZIONE.PG_OBBLIGAZIONE_SCADENZARIO = OBBLIGAZIONE_SCADENZARIO.PG_OBBLIGAZIONE_SCADENZARIO
          AND V_DOC_PASSIVO_OBBLIGAZIONE.CD_TIPO_DOCUMENTO_AMM = 'FATTURA_P'
          AND EXISTS (
            SELECT 1 FROM FATTURA_PASSIVA_RIGA FPR, FATTURA_ORDINE FO
            WHERE FPR.CD_CDS = V_DOC_PASSIVO_OBBLIGAZIONE.CD_CDS
              AND FPR.CD_UNITA_ORGANIZZATIVA = V_DOC_PASSIVO_OBBLIGAZIONE.CD_UNITA_ORGANIZZATIVA
              AND FPR.ESERCIZIO = V_DOC_PASSIVO_OBBLIGAZIONE.ESERCIZIO
              AND FPR.PG_FATTURA_PASSIVA = V_DOC_PASSIVO_OBBLIGAZIONE.PG_DOCUMENTO_AMM
              AND FPR.CD_CDS_OBBLIGAZIONE = V_DOC_PASSIVO_OBBLIGAZIONE.CD_CDS_OBBLIGAZIONE
              AND FPR.ESERCIZIO_OBBLIGAZIONE = V_DOC_PASSIVO_OBBLIGAZIONE.ESERCIZIO_OBBLIGAZIONE
              AND FPR.ESERCIZIO_ORI_OBBLIGAZIONE = V_DOC_PASSIVO_OBBLIGAZIONE.ESERCIZIO_ORI_OBBLIGAZIONE
              AND FPR.PG_OBBLIGAZIONE = V_DOC_PASSIVO_OBBLIGAZIONE.PG_OBBLIGAZIONE
              AND FPR.PG_OBBLIGAZIONE_SCADENZARIO = V_DOC_PASSIVO_OBBLIGAZIONE.PG_OBBLIGAZIONE_SCADENZARIO
              AND FO.CD_CDS = FPR.CD_CDS
              AND FO.CD_UNITA_ORGANIZZATIVA = FPR.CD_UNITA_ORGANIZZATIVA
              AND FO.ESERCIZIO = FPR.ESERCIZIO
              AND FO.PG_FATTURA_PASSIVA = FPR.PG_FATTURA_PASSIVA
              AND FO.PROGRESSIVO_RIGA = FPR.PROGRESSIVO_RIGA
        )
    ),0) IMP_ASS_FATTURA,
NVL((
        SELECT SUM(IM_TOTALE_DOC_AMM)
        FROM V_DOC_PASSIVO_OBBLIGAZIONE
        WHERE V_DOC_PASSIVO_OBBLIGAZIONE.CD_CDS_OBBLIGAZIONE = OBBLIGAZIONE_SCADENZARIO.CD_CDS
          --AND V_DOC_PASSIVO_OBBLIGAZIONE.ESERCIZIO_OBBLIGAZIONE = OBBLIGAZIONE_SCADENZARIO.ESERCIZIO
          AND V_DOC_PASSIVO_OBBLIGAZIONE.ESERCIZIO <= OBBLIGAZIONE_SCADENZARIO.ESERCIZIO
          AND V_DOC_PASSIVO_OBBLIGAZIONE.ESERCIZIO_ORI_OBBLIGAZIONE = OBBLIGAZIONE_SCADENZARIO.ESERCIZIO_ORIGINALE
          AND V_DOC_PASSIVO_OBBLIGAZIONE.PG_OBBLIGAZIONE = OBBLIGAZIONE_SCADENZARIO.PG_OBBLIGAZIONE
          AND V_DOC_PASSIVO_OBBLIGAZIONE.PG_OBBLIGAZIONE_SCADENZARIO = OBBLIGAZIONE_SCADENZARIO.PG_OBBLIGAZIONE_SCADENZARIO
          AND V_DOC_PASSIVO_OBBLIGAZIONE.CD_TIPO_DOCUMENTO_AMM NOT IN ('ORDINE')
          AND NOT EXISTS (
            SELECT 1 FROM FATTURA_PASSIVA_RIGA FPR, FATTURA_ORDINE FO
            WHERE FPR.CD_CDS = V_DOC_PASSIVO_OBBLIGAZIONE.CD_CDS
              AND FPR.CD_UNITA_ORGANIZZATIVA = V_DOC_PASSIVO_OBBLIGAZIONE.CD_UNITA_ORGANIZZATIVA
              AND FPR.ESERCIZIO = V_DOC_PASSIVO_OBBLIGAZIONE.ESERCIZIO
              AND FPR.PG_FATTURA_PASSIVA = V_DOC_PASSIVO_OBBLIGAZIONE.PG_DOCUMENTO_AMM
              AND FPR.CD_CDS_OBBLIGAZIONE = V_DOC_PASSIVO_OBBLIGAZIONE.CD_CDS_OBBLIGAZIONE
              AND FPR.ESERCIZIO_OBBLIGAZIONE = V_DOC_PASSIVO_OBBLIGAZIONE.ESERCIZIO_OBBLIGAZIONE
              AND FPR.ESERCIZIO_ORI_OBBLIGAZIONE = V_DOC_PASSIVO_OBBLIGAZIONE.ESERCIZIO_ORI_OBBLIGAZIONE
              AND FPR.PG_OBBLIGAZIONE = V_DOC_PASSIVO_OBBLIGAZIONE.PG_OBBLIGAZIONE
              AND FPR.PG_OBBLIGAZIONE_SCADENZARIO = V_DOC_PASSIVO_OBBLIGAZIONE.PG_OBBLIGAZIONE_SCADENZARIO
              AND FO.CD_CDS = FPR.CD_CDS
              AND FO.CD_UNITA_ORGANIZZATIVA = FPR.CD_UNITA_ORGANIZZATIVA
              AND FO.ESERCIZIO = FPR.ESERCIZIO
              AND FO.PG_FATTURA_PASSIVA = FPR.PG_FATTURA_PASSIVA
              AND FO.PROGRESSIVO_RIGA = FPR.PROGRESSIVO_RIGA
        )
    ),0) IMP_ASS_DOC_AMM,
TERZO.DENOMINAZIONE_SEDE,
ELEMENTO_VOCE.DS_ELEMENTO_VOCE
     FROM OBBLIGAZIONE_SCADENZARIO, OBBLIGAZIONE, TERZO, ELEMENTO_VOCE
     WHERE OBBLIGAZIONE_SCADENZARIO.ESERCIZIO_ORIGINALE=OBBLIGAZIONE.ESERCIZIO_ORIGINALE AND
                  OBBLIGAZIONE_SCADENZARIO.PG_OBBLIGAZIONE=OBBLIGAZIONE.PG_OBBLIGAZIONE AND
                  OBBLIGAZIONE_SCADENZARIO.CD_CDS=OBBLIGAZIONE.CD_CDS AND
                  OBBLIGAZIONE_SCADENZARIO.ESERCIZIO=OBBLIGAZIONE.ESERCIZIO AND
                  TERZO.CD_TERZO=OBBLIGAZIONE.CD_TERZO AND
                  (OBBLIGAZIONE.CD_TIPO_DOCUMENTO_CONT='OBB' OR
                   OBBLIGAZIONE.CD_TIPO_DOCUMENTO_CONT='OBB_RES' OR OBBLIGAZIONE.CD_TIPO_DOCUMENTO_CONT='OBB_RESIM')
       and ELEMENTO_VOCE.esercizio=obbligazione.esercizio
       and ELEMENTO_VOCE.TI_APPARTENENZA=obbligazione.TI_APPARTENENZA
       and ELEMENTO_VOCE.TI_GESTIONE=obbligazione.TI_GESTIONE
       and ELEMENTO_VOCE.CD_ELEMENTO_VOCE=obbligazione.CD_ELEMENTO_VOCE
     ORDER BY ESERCIZIO,OBBLIGAZIONE_SCADENZARIO.DT_SCADENZA, OBBLIGAZIONE_SCADENZARIO.ESERCIZIO_ORIGINALE,OBBLIGAZIONE_SCADENZARIO.PG_OBBLIGAZIONE,OBBLIGAZIONE_SCADENZARIO.PG_OBBLIGAZIONE_SCADENZARIO;

