--------------------------------------------------------
--  DDL for View V_DOCUMENTI_DA_CONTABILIZZARE
--------------------------------------------------------
CREATE OR REPLACE VIEW V_DOCUMENTI_DA_CONTABILIZZARE(TIPODOC, ESERCIZIO_CONT, ESERCIZIO, CD_CDS, CD_UNITA_ORGANIZZATIVA, PG_DOC, CD_UNITA_OPERATIVA, CD_NUMERATORE, RIGA, CONSEGNA, DT_REGISTRAZIONE) AS
SELECT 'ORDINE_CNS' TIPODOC,
       CASE WHEN EVASIONE_ORDINE_RIGA.ESERCIZIO IS NULL
                THEN ORDINE_ACQ_CONSEGNA.ESERCIZIO
            ELSE EVASIONE_ORDINE_RIGA.ESERCIZIO
           END ESERCIZIO_CONT,
       ORDINE_ACQ_CONSEGNA.ESERCIZIO,
       ORDINE_ACQ_CONSEGNA.CD_CDS,
       NULL CD_UNITA_ORGANIZZATIVA,
       ORDINE_ACQ_CONSEGNA.NUMERO PG_DOC,
       ORDINE_ACQ_CONSEGNA.CD_UNITA_OPERATIVA,
       ORDINE_ACQ_CONSEGNA.CD_NUMERATORE,
       ORDINE_ACQ_CONSEGNA.RIGA,
       ORDINE_ACQ_CONSEGNA.CONSEGNA,
       CASE WHEN EVASIONE_ORDINE_RIGA.ESERCIZIO IS NULL
            THEN ORDINE_ACQ.DATA_ORDINE
            ELSE CASE WHEN FATTURA_PASSIVA.ESERCIZIO IS NULL
                      THEN EVASIONE_ORDINE.DATA_CONSEGNA
                      ELSE CASE WHEN EVASIONE_ORDINE.DATA_CONSEGNA > FATTURA_PASSIVA.DT_REGISTRAZIONE
                                THEN FATTURA_PASSIVA.DT_REGISTRAZIONE
                                ELSE EVASIONE_ORDINE.DATA_CONSEGNA
                           END
                 END
       END DT_REGISTRAZIONE
FROM ORDINE_ACQ_CONSEGNA
LEFT JOIN ORDINE_ACQ ON ORDINE_ACQ.CD_CDS = ORDINE_ACQ_CONSEGNA.CD_CDS
    AND ORDINE_ACQ.CD_UNITA_OPERATIVA = ORDINE_ACQ_CONSEGNA.CD_UNITA_OPERATIVA
    AND ORDINE_ACQ.ESERCIZIO = ORDINE_ACQ_CONSEGNA.ESERCIZIO
    AND ORDINE_ACQ.CD_NUMERATORE = ORDINE_ACQ_CONSEGNA.CD_NUMERATORE
    AND ORDINE_ACQ.NUMERO = ORDINE_ACQ_CONSEGNA.NUMERO
LEFT OUTER JOIN EVASIONE_ORDINE_RIGA ON EVASIONE_ORDINE_RIGA.CD_CDS_ORDINE = ORDINE_ACQ_CONSEGNA.CD_CDS
    AND EVASIONE_ORDINE_RIGA.CD_UNITA_OPERATIVA = ORDINE_ACQ_CONSEGNA.CD_UNITA_OPERATIVA
    AND EVASIONE_ORDINE_RIGA.ESERCIZIO_ORDINE = ORDINE_ACQ_CONSEGNA.ESERCIZIO
    AND EVASIONE_ORDINE_RIGA.CD_NUMERATORE_ORDINE = ORDINE_ACQ_CONSEGNA.CD_NUMERATORE
    AND EVASIONE_ORDINE_RIGA.NUMERO_ORDINE = ORDINE_ACQ_CONSEGNA.NUMERO
    AND EVASIONE_ORDINE_RIGA.RIGA_ORDINE = ORDINE_ACQ_CONSEGNA.RIGA
    AND EVASIONE_ORDINE_RIGA.CONSEGNA = ORDINE_ACQ_CONSEGNA.CONSEGNA
LEFT OUTER JOIN EVASIONE_ORDINE ON EVASIONE_ORDINE.CD_CDS = EVASIONE_ORDINE_RIGA.CD_CDS_ORDINE
    AND EVASIONE_ORDINE.CD_MAGAZZINO = EVASIONE_ORDINE_RIGA.CD_MAGAZZINO
    AND EVASIONE_ORDINE.ESERCIZIO = EVASIONE_ORDINE_RIGA.ESERCIZIO
    AND EVASIONE_ORDINE.CD_NUMERATORE_MAG = EVASIONE_ORDINE_RIGA.CD_NUMERATORE_MAG
    AND EVASIONE_ORDINE.NUMERO = EVASIONE_ORDINE_RIGA.NUMERO
LEFT OUTER JOIN FATTURA_ORDINE ON FATTURA_ORDINE.CD_CDS_ORDINE = ORDINE_ACQ_CONSEGNA.CD_CDS
    AND FATTURA_ORDINE.CD_UNITA_OPERATIVA = ORDINE_ACQ_CONSEGNA.CD_UNITA_OPERATIVA
    AND FATTURA_ORDINE.ESERCIZIO_ORDINE = ORDINE_ACQ_CONSEGNA.ESERCIZIO
    AND FATTURA_ORDINE.CD_NUMERATORE = ORDINE_ACQ_CONSEGNA.CD_NUMERATORE
    AND FATTURA_ORDINE.NUMERO = ORDINE_ACQ_CONSEGNA.NUMERO
    AND FATTURA_ORDINE.RIGA = ORDINE_ACQ_CONSEGNA.RIGA
    AND FATTURA_ORDINE.CONSEGNA = ORDINE_ACQ_CONSEGNA.CONSEGNA
LEFT OUTER JOIN FATTURA_PASSIVA ON FATTURA_PASSIVA.CD_CDS = FATTURA_ORDINE.CD_CDS
    AND FATTURA_PASSIVA.ESERCIZIO = FATTURA_ORDINE.ESERCIZIO
    AND FATTURA_PASSIVA.CD_UNITA_ORGANIZZATIVA = FATTURA_ORDINE.CD_UNITA_ORGANIZZATIVA
    AND FATTURA_PASSIVA.PG_FATTURA_PASSIVA = FATTURA_ORDINE.PG_FATTURA_PASSIVA
LEFT OUTER JOIN OBBLIGAZIONE_SCADENZARIO ON OBBLIGAZIONE_SCADENZARIO.CD_CDS = ORDINE_ACQ_CONSEGNA.CD_CDS_OBBL
    AND OBBLIGAZIONE_SCADENZARIO.ESERCIZIO = ORDINE_ACQ_CONSEGNA.ESERCIZIO_OBBL
    AND OBBLIGAZIONE_SCADENZARIO.ESERCIZIO_ORIGINALE = ORDINE_ACQ_CONSEGNA.ESERCIZIO_ORIG_OBBL
    AND OBBLIGAZIONE_SCADENZARIO.PG_OBBLIGAZIONE = ORDINE_ACQ_CONSEGNA.PG_OBBLIGAZIONE
    AND OBBLIGAZIONE_SCADENZARIO.PG_OBBLIGAZIONE_SCADENZARIO = ORDINE_ACQ_CONSEGNA.PG_OBBLIGAZIONE_SCAD
WHERE ORDINE_ACQ.STATO = 'DEF'
AND NVL(ORDINE_ACQ_CONSEGNA.STATO, 'X') != 'EVF'
AND NVL(ORDINE_ACQ_CONSEGNA.IM_TOTALE_CONSEGNA, 0) != 0
AND NVL(EVASIONE_ORDINE_RIGA.STATO, 'INS') = 'INS'
AND (ORDINE_ACQ_CONSEGNA.STATO_COGE = 'N' OR ORDINE_ACQ_CONSEGNA.STATO_COGE = 'R')
AND (ORDINE_ACQ_CONSEGNA.CD_VOCE_EP IS NULL OR
     EVASIONE_ORDINE_RIGA.ESERCIZIO IS NOT NULL OR FATTURA_PASSIVA.ESERCIZIO IS NOT NULL OR
     (ORDINE_ACQ_CONSEGNA.ESERCIZIO_OBBL IS NOT NULL AND OBBLIGAZIONE_SCADENZARIO.IM_SCADENZA != 0 AND
	    NOT EXISTS(SELECT '1' FROM ORDINE_ACQ_CONSEGNA_ECO
  	               WHERE ORDINE_ACQ_CONSEGNA_ECO.CD_CDS = ORDINE_ACQ_CONSEGNA.CD_CDS
   				   AND ORDINE_ACQ_CONSEGNA_ECO.CD_UNITA_OPERATIVA = ORDINE_ACQ_CONSEGNA.CD_UNITA_OPERATIVA
    			   AND ORDINE_ACQ_CONSEGNA_ECO.ESERCIZIO = ORDINE_ACQ_CONSEGNA.ESERCIZIO
    			   AND ORDINE_ACQ_CONSEGNA_ECO.CD_NUMERATORE = ORDINE_ACQ_CONSEGNA.CD_NUMERATORE
    			   AND ORDINE_ACQ_CONSEGNA_ECO.NUMERO = ORDINE_ACQ_CONSEGNA.NUMERO
    			   AND ORDINE_ACQ_CONSEGNA_ECO.RIGA = ORDINE_ACQ_CONSEGNA.RIGA
    			   AND ORDINE_ACQ_CONSEGNA_ECO.CONSEGNA = ORDINE_ACQ_CONSEGNA.CONSEGNA)))
UNION ALL
SELECT 'ANTICIPO' TIPODOC,
       ANTICIPO.ESERCIZIO ESERCIZIO_CONT,
       ANTICIPO.ESERCIZIO,
       ANTICIPO.CD_CDS,
       ANTICIPO.CD_UNITA_ORGANIZZATIVA,
       ANTICIPO.PG_ANTICIPO PG_DOC,
       NULL CD_UNITA_OPERATIVA,
       NULL CD_NUMERATORE,
       NULL RIGA,
       NULL CONSEGNA,
       ANTICIPO.DT_REGISTRAZIONE
FROM ANTICIPO
WHERE (ANTICIPO.STATO_COGE = 'N' OR ANTICIPO.STATO_COGE = 'R')
UNION ALL
SELECT 'MISSIONE' TIPODOC,
       MISSIONE.ESERCIZIO ESERCIZIO_CONT,
       MISSIONE.ESERCIZIO,
       MISSIONE.CD_CDS,
       MISSIONE.CD_UNITA_ORGANIZZATIVA,
       MISSIONE.PG_MISSIONE PG_DOC,
       NULL CD_UNITA_OPERATIVA,
       NULL CD_NUMERATORE,
       NULL RIGA,
       NULL CONSEGNA,
       MISSIONE.DT_REGISTRAZIONE
FROM MISSIONE
WHERE (MISSIONE.STATO_COGE = 'N' OR MISSIONE.STATO_COGE = 'R')
UNION ALL
SELECT 'COMPENSO' TIPODOC,
       COMPENSO.ESERCIZIO ESERCIZIO_CONT,
       COMPENSO.ESERCIZIO,
       COMPENSO.CD_CDS,
       COMPENSO.CD_UNITA_ORGANIZZATIVA,
       COMPENSO.PG_COMPENSO PG_DOC,
       NULL CD_UNITA_OPERATIVA,
       NULL CD_NUMERATORE,
       NULL RIGA,
       NULL CONSEGNA,
       COMPENSO.DT_REGISTRAZIONE
FROM COMPENSO
WHERE (COMPENSO.STATO_COGE = 'N' OR COMPENSO.STATO_COGE = 'R')
UNION ALL
SELECT 'RIMBORSO' TIPODOC,
       RIMBORSO.ESERCIZIO ESERCIZIO_CONT,
       RIMBORSO.ESERCIZIO,
       RIMBORSO.CD_CDS,
       RIMBORSO.CD_UNITA_ORGANIZZATIVA,
       RIMBORSO.PG_RIMBORSO PG_DOC,
       NULL CD_UNITA_OPERATIVA,
       NULL CD_NUMERATORE,
       NULL RIGA,
       NULL CONSEGNA,
       RIMBORSO.DT_REGISTRAZIONE
FROM RIMBORSO
WHERE (RIMBORSO.STATO_COGE = 'N' OR RIMBORSO.STATO_COGE = 'R')
UNION ALL
SELECT DOCUMENTO_GENERICO.CD_TIPO_DOCUMENTO_AMM TIPODOC,
       DOCUMENTO_GENERICO.ESERCIZIO ESERCIZIO_CONT,
       DOCUMENTO_GENERICO.ESERCIZIO,
       DOCUMENTO_GENERICO.CD_CDS,
       DOCUMENTO_GENERICO.CD_UNITA_ORGANIZZATIVA,
       DOCUMENTO_GENERICO.PG_DOCUMENTO_GENERICO PG_DOC,
       NULL CD_UNITA_OPERATIVA,
       NULL CD_NUMERATORE,
       NULL RIGA,
       NULL CONSEGNA,
       DOCUMENTO_GENERICO.DATA_REGISTRAZIONE
FROM DOCUMENTO_GENERICO
WHERE (DOCUMENTO_GENERICO.STATO_COGE = 'N' OR DOCUMENTO_GENERICO.STATO_COGE = 'R')
UNION ALL
SELECT CASE WHEN TI_FATTURA = 'C'
                THEN 'NOTA_CREDITO_A'
            ELSE CASE WHEN TI_FATTURA = 'D'
                          THEN 'NOTA_DEBITO_A'
                      ELSE 'FATTURA_A'
                END
           END TIPODOC,
       FATTURA_ATTIVA.ESERCIZIO ESERCIZIO_CONT,
       FATTURA_ATTIVA.ESERCIZIO,
       FATTURA_ATTIVA.CD_CDS,
       FATTURA_ATTIVA.CD_UNITA_ORGANIZZATIVA,
       FATTURA_ATTIVA.PG_FATTURA_ATTIVA PG_DOC,
       NULL CD_UNITA_OPERATIVA,
       NULL CD_NUMERATORE,
       NULL RIGA,
       NULL CONSEGNA,
       FATTURA_ATTIVA.DT_REGISTRAZIONE
FROM FATTURA_ATTIVA
WHERE (FATTURA_ATTIVA.STATO_COGE = 'N' OR FATTURA_ATTIVA.STATO_COGE = 'R')
UNION ALL
SELECT CASE WHEN TI_FATTURA = 'C'
                THEN 'NOTA_CREDITO_P'
            ELSE CASE WHEN TI_FATTURA = 'D'
                          THEN 'NOTA_DEBITO_P'
                      ELSE 'FATTURA_P'
                END
           END TIPODOC,
       FATTURA_PASSIVA.ESERCIZIO ESERCIZIO_CONT,
       FATTURA_PASSIVA.ESERCIZIO,
       FATTURA_PASSIVA.CD_CDS,
       FATTURA_PASSIVA.CD_UNITA_ORGANIZZATIVA,
       FATTURA_PASSIVA.PG_FATTURA_PASSIVA PG_DOC,
       NULL CD_UNITA_OPERATIVA,
       NULL CD_NUMERATORE,
       NULL RIGA,
       NULL CONSEGNA,
       FATTURA_PASSIVA.DT_REGISTRAZIONE
FROM FATTURA_PASSIVA
WHERE (FATTURA_PASSIVA.STATO_COGE = 'N' OR FATTURA_PASSIVA.STATO_COGE = 'R')
UNION ALL
SELECT 'MAN' TIPODOC,
       MANDATO.ESERCIZIO ESERCIZIO_CONT,
       MANDATO.ESERCIZIO,
       MANDATO.CD_CDS,
       MANDATO.CD_UNITA_ORGANIZZATIVA,
       MANDATO.PG_MANDATO PG_DOC,
       NULL CD_UNITA_OPERATIVA,
       NULL CD_NUMERATORE,
       NULL RIGA,
       NULL CONSEGNA,
       CASE WHEN MANDATO.DT_PAGAMENTO != NULL
    THEN MANDATO.DT_PAGAMENTO
    ELSE MANDATO.DT_EMISSIONE
END DT_REGISTRAZIONE
FROM MANDATO
WHERE (MANDATO.STATO_COGE = 'N' OR MANDATO.STATO_COGE = 'R')
UNION ALL
SELECT 'REV' TIPODOC,
       REVERSALE.ESERCIZIO ESERCIZIO_CONT,
       REVERSALE.ESERCIZIO,
       REVERSALE.CD_CDS,
       REVERSALE.CD_UNITA_ORGANIZZATIVA,
       REVERSALE.PG_REVERSALE PG_DOC,
       NULL CD_UNITA_OPERATIVA,
       NULL CD_NUMERATORE,
       NULL RIGA,
       NULL CONSEGNA,
       CASE WHEN REVERSALE.DT_INCASSO != NULL
    THEN REVERSALE.DT_INCASSO
    ELSE REVERSALE.DT_EMISSIONE
END DT_REGISTRAZIONE
FROM REVERSALE
WHERE (REVERSALE.STATO_COGE = 'N' OR REVERSALE.STATO_COGE = 'R');