--------------------------------------------------------
--  DDL for View V_PARTITARIO
--------------------------------------------------------
  CREATE OR REPLACE FORCE VIEW "V_PARTITARIO" (
    "PG_SCRITTURA",
    "DT_CONTABILIZZAZIONE",
    "DS_SCRITTURA",
    "ESERCIZIO",
    "PG_MOVIMENTO",
    "CD_UNITA_ORGANIZZATIVA",
    "CD_CDS",
    "CD_RIGA",
    "SEZIONE",
    "CD_VOCE_EP",
    "CD_TERZO",
    "TI_RIGA",
    "CD_CONTRIBUTO_RITENUTA",
    "ESERCIZIO_DOCUMENTO",
    "CD_TIPO_DOCUMENTO",
    "CD_CDS_DOCUMENTO",
    "CD_UO_DOCUMENTO",
    "PG_NUMERO_DOCUMENTO",
    "NR_FATTURA_FOR_PAG",
    "DT_EM_PAG",
    "STATO_LIQUIDAZIONE",
    "IDENTIFICATIVO_SDI",
    "IM_MOVIMENTO_DARE",
    "IM_MOVIMENTO_AVERE",
    "DIFFERENZA"
  ) AS SELECT
--
-- Date: 11/09/2022
-- Version: 1.0
--
-- Vista di estrazione delle Partite di Economico Patrimoniale
--
-- History:
--
-- Date: 11/09/2022
-- Version: 1.0
-- Creazione
--
-- Date: 20/01/2025
-- Version: 1.1
-- Aggiunte le informazioni Descrizione/denominazione/ragione sociale terzo
-- Numero fattura del terzo (dopo numero progressivo), oppure numero mandato pagamento-reversale incasso-nota di credito a seconda del movimento registrato sul partitario
-- Data emissione fattura del terzo, oppure data mandato-reversale-nota di credito a seconda del movimento registrato sul partitario
-- Stato liquidazione
--
-- Body:
--
MC.PG_SCRITTURA,
SPD.DT_CONTABILIZZAZIONE,
SPD.DS_SCRITTURA,
MC.ESERCIZIO,
MC.PG_MOVIMENTO,
MC.CD_UNITA_ORGANIZZATIVA,
MC.CD_CDS,
'D' CD_RIGA,
MC.SEZIONE,
MC.CD_VOCE_EP,
MC.CD_TERZO,
MC.TI_RIGA,
NVL(MC.CD_CONTRIBUTO_RITENUTA, ' '),
MC.ESERCIZIO_DOCUMENTO,
MC.CD_TIPO_DOCUMENTO,
MC.CD_CDS_DOCUMENTO,
MC.CD_UO_DOCUMENTO,
MC.PG_NUMERO_DOCUMENTO,
CASE WHEN SPD.ORIGINE_SCRITTURA = 'DOCCONT' THEN TO_CHAR(NVL(M.PG_MANDATO, R.PG_REVERSALE)) ELSE
    CASE WHEN MC.CD_TIPO_DOCUMENTO = 'FATTURA_P' THEN FP.NR_FATTURA_FORNITORE ELSE NULL END
END NR_FATTURA_FOR_PAG,
CASE WHEN SPD.ORIGINE_SCRITTURA = 'DOCCONT' THEN NVL(M.DT_EMISSIONE, R.DT_EMISSIONE) ELSE
    CASE WHEN MC.CD_TIPO_DOCUMENTO = 'FATTURA_P' THEN FP.DT_REGISTRAZIONE
         WHEN MC.CD_TIPO_DOCUMENTO = 'FATTURA_A' THEN FA.DT_REGISTRAZIONE
    END
END DT_EM_PAG,
CASE WHEN MC.CD_TIPO_DOCUMENTO = 'FATTURA_P' AND SPD.ORIGINE_SCRITTURA = 'DOCAMM' THEN FP.STATO_LIQUIDAZIONE
    WHEN MC.CD_TIPO_DOCUMENTO = 'COMPENSO' AND SPD.ORIGINE_SCRITTURA = 'DOCAMM' THEN C.STATO_LIQUIDAZIONE
    ELSE NULL END STATO_LIQUIDAZIONE,
CASE WHEN MC.CD_TIPO_DOCUMENTO = 'FATTURA_P' THEN FP.IDENTIFICATIVO_SDI
     WHEN MC.CD_TIPO_DOCUMENTO = 'FATTURA_A' THEN TO_NUMBER(FA.CODICE_INVIO_SDI) ELSE NULL END IDENTIFICATIVO_SDI,
Decode (MC.SEZIONE,'D',IM_MOVIMENTO,null) IM_MOVIMENTO_DARE,
Decode (MC.SEZIONE,'A',IM_MOVIMENTO,null) IM_MOVIMENTO_AVERE,
NULL DIFFERENZA
FROM MOVIMENTO_COGE MC
JOIN SCRITTURA_PARTITA_DOPPIA SPD ON SPD.ESERCIZIO = MC.ESERCIZIO AND SPD.CD_CDS = MC.CD_CDS AND SPD.PG_SCRITTURA = MC.PG_SCRITTURA AND SPD.CD_UNITA_ORGANIZZATIVA = MC.CD_UNITA_ORGANIZZATIVA
LEFT OUTER JOIN COMPENSO C ON C.CD_CDS = MC.CD_CDS_DOCUMENTO AND C.CD_UNITA_ORGANIZZATIVA = MC.CD_UO_DOCUMENTO
    AND C.ESERCIZIO = MC.ESERCIZIO_DOCUMENTO AND C.PG_COMPENSO = MC.PG_NUMERO_DOCUMENTO
LEFT OUTER JOIN FATTURA_PASSIVA FP ON FP.CD_CDS = MC.CD_CDS_DOCUMENTO AND FP.CD_UNITA_ORGANIZZATIVA = MC.CD_UO_DOCUMENTO
    AND FP.ESERCIZIO = MC.ESERCIZIO_DOCUMENTO AND FP.PG_FATTURA_PASSIVA = MC.PG_NUMERO_DOCUMENTO
LEFT OUTER JOIN FATTURA_ATTIVA FA ON FA.CD_CDS = MC.CD_CDS_DOCUMENTO AND FA.CD_UNITA_ORGANIZZATIVA = MC.CD_UO_DOCUMENTO
    AND FA.ESERCIZIO = MC.ESERCIZIO_DOCUMENTO AND FA.PG_FATTURA_ATTIVA = MC.PG_NUMERO_DOCUMENTO
LEFT OUTER JOIN DOCUMENTO_GENERICO DG ON DG.CD_TIPO_DOCUMENTO_AMM = MC.CD_TIPO_DOCUMENTO AND DG.CD_CDS = MC.CD_CDS_DOCUMENTO AND DG.CD_UNITA_ORGANIZZATIVA = MC.CD_UO_DOCUMENTO
    AND DG.ESERCIZIO = MC.ESERCIZIO_DOCUMENTO AND DG.PG_DOCUMENTO_GENERICO = MC.PG_NUMERO_DOCUMENTO
LEFT OUTER JOIN MANDATO M ON SPD.CD_TIPO_DOCUMENTO = 'MAN' AND M.CD_CDS = SPD.CD_CDS_DOCUMENTO AND M.ESERCIZIO = SPD.ESERCIZIO AND M.PG_MANDATO = SPD.PG_NUMERO_DOCUMENTO
LEFT OUTER JOIN REVERSALE R ON SPD.CD_TIPO_DOCUMENTO = 'REV' AND R.CD_CDS = SPD.CD_CDS_DOCUMENTO AND R.ESERCIZIO = SPD.ESERCIZIO AND R.PG_REVERSALE = SPD.PG_NUMERO_DOCUMENTO
UNION ALL
SELECT
MAX(MOVIMENTO_COGE.PG_SCRITTURA),
MIN(SCRITTURA_PARTITA_DOPPIA.DT_CONTABILIZZAZIONE),
MAX(SCRITTURA_PARTITA_DOPPIA.DS_SCRITTURA),
MAX(MOVIMENTO_COGE.ESERCIZIO),
MAX(MOVIMENTO_COGE.PG_MOVIMENTO),
MAX(MOVIMENTO_COGE.CD_UNITA_ORGANIZZATIVA),
MAX(MOVIMENTO_COGE.CD_CDS),
'T' CD_RIGA,
NULL SEZIONE,
NULL CD_VOCE_EP,
MAX(MOVIMENTO_COGE.CD_TERZO) CD_TERZO,
MAX('SALDO') TI_RIGA,
NVL(MOVIMENTO_COGE.CD_CONTRIBUTO_RITENUTA, ' '),
MOVIMENTO_COGE.ESERCIZIO_DOCUMENTO,
MOVIMENTO_COGE.CD_TIPO_DOCUMENTO,
MOVIMENTO_COGE.CD_CDS_DOCUMENTO,
MOVIMENTO_COGE.CD_UO_DOCUMENTO,
MOVIMENTO_COGE.PG_NUMERO_DOCUMENTO,
NULL NR_FATTURA_FOR_PAG,
NULL DT_EM_PAG,
NULL STATO_LIQUIDAZIONE,
NULL IDENTIFICATIVO_SDI,
NULL IM_MOVIMENTO_DARE,
NULL IM_MOVIMENTO_AVERE,
SUM(Decode (SEZIONE,'D',NVL(IM_MOVIMENTO,0),NVL(-IM_MOVIMENTO,0))) DIFFERENZA
FROM MOVIMENTO_COGE, SCRITTURA_PARTITA_DOPPIA WHERE
( SCRITTURA_PARTITA_DOPPIA.ESERCIZIO=MOVIMENTO_COGE.ESERCIZIO ) AND
( SCRITTURA_PARTITA_DOPPIA.CD_CDS=MOVIMENTO_COGE.CD_CDS ) AND
( SCRITTURA_PARTITA_DOPPIA.PG_SCRITTURA=MOVIMENTO_COGE.PG_SCRITTURA ) AND
( SCRITTURA_PARTITA_DOPPIA.CD_UNITA_ORGANIZZATIVA=MOVIMENTO_COGE.CD_UNITA_ORGANIZZATIVA ) AND
( SCRITTURA_PARTITA_DOPPIA.DT_CANCELLAZIONE IS NULL)
GROUP BY MOVIMENTO_COGE.ESERCIZIO_DOCUMENTO,
    MOVIMENTO_COGE.CD_TIPO_DOCUMENTO,
    MOVIMENTO_COGE.CD_CDS_DOCUMENTO,
    MOVIMENTO_COGE.CD_UO_DOCUMENTO,
    MOVIMENTO_COGE.PG_NUMERO_DOCUMENTO,
    MOVIMENTO_COGE.CD_CONTRIBUTO_RITENUTA
;
