#
# Copyright (C) 2019  Consiglio Nazionale delle Ricerche
#
#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU Affero General Public License as
#     published by the Free Software Foundation, either version 3 of the
#     License, or (at your option) any later version.
#
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU Affero General Public License for more details.
#
#     You should have received a copy of the GNU Affero General Public License
#     along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
CRUDToolbar.elabora.img=img/import24.gif
CRUDToolbar.elabora.disabledImg=img/import24.gif
CRUDToolbar.elabora.label=<u>E</u>labora dati
CRUDToolbar.elabora.href=javascript:submitForm('doElaboraDati')
CRUDToolbar.elabora.style=width:60px;
CRUDToolbar.elabora.separator=true
CRUDToolbar.elabora.accessKey=E
CRUDToolbar.elabora.title=Elabora Dati
CRUDToolbar.elabora.buttonClass=btn-title btn-outline-primary
CRUDToolbar.elabora.iconClass=fa fa-2x fa-fw fa-bolt

CRUDToolbar.refresh.img=img/import24.gif
CRUDToolbar.refresh.disabledImg=img/import24.gif
CRUDToolbar.refresh.label=<u>A</u>ggiorna
CRUDToolbar.refresh.href=javascript:submitForm('doRefresh')
CRUDToolbar.refresh.style=width:60px;
CRUDToolbar.refresh.accessKey=A
CRUDToolbar.refresh.title=Aggiorna
CRUDToolbar.refresh.buttonClass=btn-title btn-outline-primary
CRUDToolbar.refresh.iconClass=fa fa-2x fa-fw fa-refresh

CRUDToolbar.delete.img=img/delete24.gif
CRUDToolbar.delete.disabledImg=img/delete24.gif
CRUDToolbar.delete.label=<u>E</u>limina;
CRUDToolbar.delete.href=javascript:submitForm('doElimina')
CRUDToolbar.delete.style=width:60px;
CRUDToolbar.delete.accessKey=E
CRUDToolbar.delete.separator=true
CRUDToolbar.delete.title=Elimina
CRUDToolbar.delete.iconClass=fa fa-2x fa-fw fa-trash
CRUDToolbar.delete.buttonClass=btn-outline-danger btn-title