  name: Release Packages

  on:
    release:
      types:
        - created

  jobs:
    release:
      runs-on: ubuntu-latest

      permissions:
        contents: write
        packages: write

      steps:
        - uses: actions/checkout@v4
          with:
            ref: master

        - uses: actions/setup-java@v4
          with:
            java-version: '21'
            distribution: 'temurin'
            cache: 'maven'

        - name: Check active Maven profiles
          run: |
            mvn help:active-profiles -s .m2/settings.xml -PAZURE,PROD,iss
          env:
            GITHUB_USERNAME: ${{ github.actor }}
            GITHUB_TOKEN: ${{ secrets.ISS_PAT }}

        - name: Set release version
          run: |
            mvn -B versions:set \
              -DnewVersion=${{ github.event.release.tag_name }} \
              -DgenerateBackupPoms=false

        - name: Deploy release
          run: |
            mvn clean deploy \
              -s .m2/settings.xml \
              -PAZURE,PROD,iss \
              -Darguments="-DskipTests" \
              -DskipTests \
              --batch-mode --errors --fail-at-end --show-version
          env:
            GITHUB_USERNAME: ${{ github.actor }}
            GITHUB_TOKEN: ${{ secrets.ISS_PAT }}

        - name: Log in to GitHub Container Registry
          run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

        - name: Build Docker image
          run: |
            docker build -t ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }} .

        - name: Push Docker image
          run: |
            docker push ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }}

        - name: Set next SNAPSHOT version
          run: |
            mvn -B versions:set \
              -DnewVersion=${{ github.event.release.tag_name }}-SNAPSHOT \
              -DgenerateBackupPoms=false

        - name: Commit and push changes
          run: |
            git config --global user.email "dirgensa@iss.it"
            git config --global user.name "dirgensa"
            
            git add pom.xml
            git commit -m "Bumped version to ${{ github.event.release.tag_name }}-SNAPSHOT" || echo "No changes to commit"
            git push origin master