name: Release Packages
on:
  release:
    types: [created]
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'master'
      - uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Update version in pom.xml (Release only) and deploy to Github Package Registry
        run: |
          mvn -B versions:set -DnewVersion=${{ github.event.release.tag_name }} -DgenerateBackupPoms=false
          mvn clean deploy -s .m2/settings.xml -PAZURE --batch-mode --errors --fail-at-end --show-version
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/sigla-wildfly:${{ github.event.release.tag_name }} .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/sigla-wildfly:${{ github.event.release.tag_name }}

      - name: Update version in pom.xml width SNAPSHOT version
        run: |
          mvn -B versions:set -DnewVersion=${{ github.event.release.tag_name }}-SNAPSHOT -DgenerateBackupPoms=false
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit and push changes to pom.
        run: |
          git config --global user.email "dirgensa@iss.it"
          git config --global user.name "dirgensa"
          git add pom.xml
          git commit -m "Bumped version to ${{ github.event.release.tag_name }}"
          git push
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}